<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 210%;text-align: center;border-radius: 10px 70px">
      NLP -Text Preprocessing-Big Data Midterm Exam
</center></p></h1>

<a class="anchor" id="data"></a>
<br>
<br>
<br>
<font style="font-family:Gabriola; font-size:300%;">Libraries
 </font><br>
 <br>

In [2]:

import pandas as pd  
import numpy as np              


import re               
import string         
from wordcloud import WordCloud 
import nltk            
from nltk.corpus import stopwords, wordnet
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize, sent_tokenize



nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

True

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
      Data Loading  
</center></p></h1>

### load datasets

In [5]:
df=pd.read_csv(r'D:\Data Analysis- Scientist\Projects\Biga Data,Text Preprocessing & NLP\Big Data -Text Preprocessing\dataset.csv', header=None)
df.head()

                                                   0
0  my teachers seeing me submit my assignment at ...
1  My uncle just got married. My uncle just got m...
2  This is sad. The story of this girls break up....
3  How much reddit karma is considered a lot? Two...
4  cat attack my cat decided to jump out from und...

In [8]:
df.columns=[ "reviews"]

In [9]:
df.head(5)

                                             reviews
0  my teachers seeing me submit my assignment at ...
1  My uncle just got married. My uncle just got m...
2  This is sad. The story of this girls break up....
3  How much reddit karma is considered a lot? Two...
4  cat attack my cat decided to jump out from und...

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
     Text Preprocessing 
</center></p></h1>



Text is the most unstructured form of all the available data, therefore various types of noise are present in it. This means that the data is not readily analyzable without any pre-processing. The entire process of cleaning and standardization of text, making it noise-free and ready for analysis is known as **text preprocessing**.

The three key steps of text preprocessing:

- **Tokenization:**
This step is one of the top priorities when it comes to working on text mining. Tokenization is essentially splitting a phrase, sentence, paragraph, or an entire text document into smaller units, such as individual words or terms. Each of these smaller units are called tokens.

- **Noise Removal:**
Any piece of text which is not relevant to the context of the data and the end-output can be specified as the noise.
For example – language stopwords (commonly used words of a language – is, am, the, of, in etc), URLs or links, upper and lower case differentiation, punctuations and industry specific words. This step deals with removal of all types of noisy entities present in the text.


- **Lexicon Normalization:**
Another type of textual noise is about the multiple representations exhibited by single word.
For example – “play”, “player”, “played”, “plays” and “playing” are the different variations of the word – “play”. Though they mean different things, contextually they all are similar. This step converts all the disparities of a word into their normalized form (also known as lemma).
There are two methods of lexicon normalisation; **[Stemming or Lemmatization](https://www.guru99.com/stemming-lemmatization-python-nltk.html)**. Lemmatization is recommended for this case, because Lemmatization as this will return the root form of each word (rather than just stripping suffixes, which is stemming).

As the first step change text to tokens and convertion all of the words to lower case.  Next remove punctuation, bad characters, numbers and stop words. The second step is aimed to normalization them throught the Lemmatization method.

In [3]:
data = df.to_string() 
data

"                                                                                                                                                                                                                                                                                                                                                                                                                                                   0\n0                                                                                                                                                                                                                                                          my teachers seeing me submit my assignment at 3am again: 👁️👄👁️ i wonder if my teachers are silently judging me :/\\n\\n\\n\\n&amp;#x200B;\\n\\n\\n\\nfiller filter flicker snicker bicker clicker\n1                                                                                                                                                                                                               My uncle just got married. My uncle just got married to a beautiful wife and I would like to present him with something. I couldn’t think of anything else but to tell you guys. Congratulations Uncle Jeremy! I’m so happy for you!\n2                                                                                                                                                                                                     This is sad. The story of this girls break up. https://www.reddit.com/r/Advice/comments/jco47r/im_only_13_and_im_being_stressed_over_some_stupid/?utm_medium=android_app&amp;utm_source=share\\n\\n\\n\\nI dont need any karma, go and suport her.\n3                                                                                                                                                                                                            How much reddit karma is considered a lot? Two days ago marked my 1 year anniversary of being on reddit. And in that time I have accumulated a bit more than 80,000 karma. So I was just wondering, how much karma is considered a lot?\n4                                                                                                                                                                                                            cat attack my cat decided to jump out from underneath a chair and attack me he barely even scratched me but my cat is annoying his name is Eddy/Edmond he's always surprising us because most of the time he's super friendly fun times\n5                                                                                                                                                                                                             The first YouTube video was made closer to 1989 than it was to today Look at the months. It has been 15 years and 5 months since the video was made, and back then the video was made 15 years and 4 months away from December of 1989\n6                                                                                                                                                                                                       Why do Chinese people speak Chinese when it is very difficult? They should just learn and easier language like English or Spanish. They speak like 8 languages in China but I won't list them.\\n\\n\\n\\nEdit : actually they speak a lot more.\n7                                                                                                                                                                                                                                                                                                                             Ok who should I draw a portrait of I'm bored and need inspiration so yeah. Idk, ig I'll pick my favorite and draw that\n8                                                                                                                                                                                                                                                                                                                             Can you recommend me any music to listen to So I'm bored and can't fall asleep do you guys know any good songs, bands?\n9                                                                                                                                                                                                                                                                                                                               I tried saying can i get 1mil subs for no reason and got a lot of hate, boy it’s a joke https://youtu.be/exobRyhH5fg\n10                                                                                                                                                                                                                                                                                                                             Are you guys allowed to switch off your cameras during online class? Because I'm not Maybe it's an American thing idk\n11                                                                                                                                                                                                                                                                                                                             To anyone here who is worried about college remember one thing If Kaitlyn Bennett can get through college you can too\n12                                                                                                                                                                                                                                                                                                                             I finally did it!! After a year with my Learner's Permit, I finally took the Driver's License test today and passed!!\n13                                                                                                                                                                                                                                                                                                                          Reddit costs $1.8 billion If we raise the money we can buy Reddit to make things crash quicker\\n\\nPlease spread the news\n14                                                                                                                                                                                                                                                                                                                     God the princess and the frog is such an         underrated Disney princess movie Probably my favorite Disney princess movies\n15                                                                                                                                                                                                                                                                                                                          If you want to feel wanted by someone Just rob a bankkkk, now the whole police will be looking for you. Works everytime.\n16                                                                                                                                                                                                                                                                                                                                                                                    why are you all so depressed Stop being depressed just be hapy\n17                                                                                                                                                                                                                                                                                                                              Draw with me part 2 [https://r7.whiteboardfox.com/7691988-9928-1785](https://r7.whiteboardfox.com/7691988-9928-1785)\n18                                                                                                                                                                                                                                                                                                                              Why do people hate British uniforms? They all look so pretty, I don't understand why people think that they're ugly.\n19                                                                                                                                                                                                                                                                                                                             How do i join minecraft serves through my ps4? I recently bought minecraft so don't know \\nAlso is ps plus necessary?\n20                                                                                                                                                                                                                                                                                                                               I got an A for writing an essay on a book I didn't read. It was an in clas write so I only had 55 minutes to do it.\n21                                                                                                                                                                                                                                                                                                                        Yo let's chat, hmu if you are interested Tryna make some friiiieeeennndddsssssssssssssssssssssssssss\\n\\n\\n\\nAlso I'm bored\n22                                                                                                                                                                                                                                                                         Why does the thought of dieing make me hapy?I have a pllan. it's going to happen. If i wasn't waiting on something I would go right now. Why do these thoughts excite me?\n23                                                                                                                                                                                                                                  i'm still alive, but I'm deleting my Reddit tomorrowthanks for all the kind messages and all, but this place is too fucking toxic to continue being here. if u wanna talk to me, I have discord: aquamarine#3232\n24                                                                                                                                                                                                                                                                                                                                 Writing something positive about my day, day #261 I slept for a while the night before so I wasn’t as tired today\n25                                                                                                                                                                                                                                                                                                                               Fun Fact: You are never not using your skeleton #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #\n26                                                                                                                                                                                                                                                                                                                             It’s not even 5 yet and it’s dark outside WHYYYYYY\\n\\n\\n\\nThis is getting ridiculous. The sun needs to stop slacking.\n27                                                                                                                                                                                                                                                                                                                   I am listening to songs..... SDCARD/Music/Hans Zimmer/Inception/Mombasa.wav\\n\\n\\n\\n\\n\\n\\n\\nWith Surround Sound ON on SoundAlive\n28                                                                                                                                                                                                                                                                                                                                Is it just me... That has thoughts about cringy/embarrassing alternate scenarios that almost hapened in your life?\n29                                                                                                                                                                                                                                                                                                                                 Name Your Mood And I’ll Recommend A Song Will try to pick a song that you will enjoy based on your mood. Enjoy :)\n30                                                                                                                                                                                                                                                                                                                             Whats a #song you can recommend to everyone No matter what #genre they like, what song can you recommend to everyone?\n31                                                                                                                                                                                                                                                                                                       How do I change my iOS 14 app logos to my own photos? I’m being honestly I do not know how to change my app logos           #heeelllllppppp\n32                                                                                                                                                                                                                                                                                                                         Spicy fried chicken &gt;&gt;&gt;&gt;&gt; the spice, the tender meat, the aroma\\n\\n\\n\\neverything about it is just so good\n33                                                                                                                                                                                                                                                                                                                                                                S.T.A.L.K.E.R., Metro, or Fallout? I just want to hear your opiniuns on the games.\n34                                                                                                                                                                                                                                                                                                                                                                    Funniest comment gets free “helpful” award because I really need to laugh... E\n35                                                                                                                                                                                                                                                                                                                                                                Lalalalalalalalalalalalalalalalalalalalalalala BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRB\n36                                                                                                                                                                                                                                                                                                                                                                              I dont like emojis But i can make exceptions for this ones\\n\\n🚹🕎🔯♻️🧼\n37                                                                                                                                                                                                                                                                                                                                                           WILLIAMS' GOT AN INVESTMENT!! I don't know about investments but\\n\\n\\n\\nGO WILLIAMS GO.\n38                                                                                                                                                                                                                                                                                                                                                                 u/coolstarfish55 is my favorite redditor u/coolstarfish55 is my favorite redditor\n39                                                                                                                                                                                                                                                                                                                                                                 Now I'll be the best user of teenagers And my competitors will be turned to stone\n40                                                                                                                                                                                                                                                                     methodsjust a purely theoretic discussion about the easiest ways out. what would be your prefered way? with the least impact to your family and least destruction of body? \\n\n41                                                                                                                                                                                                                                         Sleeping pillsHow to kill myself most effectively using sleeping pills and alcohol (like vodka)? I don't want to end up being a vegetable. Only that holds me back, that's why I'm asking you my friends.\n42                          someone please, please tell me not toim not a good person and i want it to stop i want itt o stop so b ad but i'm scared of what would happen but i just want it over i don't know what to do. i hurt my friends and t hey stalked me but it was my fault in the first plae c and all they saw was lies lies lies lies lies . about Them\\n\\n\\n\\ni don't think g-d wants me here anymore. i think im supposed to be  gone\n43                                                                                                                                                                                                                                                           Have 60 - 1mg Xanax. Thinking about taking them all. Don't know why I'm even postingIt's all too much. It hurts everyday. My sleep is only when I have peace. I just want that forever.\n44                                                                                                                                                                                                                                             

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
      Data Cleaning Steps
</center></p></h1>

### a. Remove newlines and Tabs

In [4]:
clean_data = data.replace("\\n", " ") # remove new lines \n
clean_data = clean_data.replace("\\t", " ") # remove tabs
clean_data = re.sub(re.compile(r'\s+'), " ", clean_data) # remove white spaces

clean_data

" 0 0 my teachers seeing me submit my assignment at 3am again: 👁️👄👁️ i wonder if my teachers are silently judging me :/ &amp;#x200B; filler filter flicker snicker bicker clicker 1 My uncle just got married. My uncle just got married to a beautiful wife and I would like to present him with something. I couldn’t think of anything else but to tell you guys. Congratulations Uncle Jeremy! I’m so happy for you! 2 This is sad. The story of this girls break up. https://www.reddit.com/r/Advice/comments/jco47r/im_only_13_and_im_being_stressed_over_some_stupid/?utm_medium=android_app&amp;utm_source=share I dont need any karma, go and suport her. 3 How much reddit karma is considered a lot? Two days ago marked my 1 year anniversary of being on reddit. And in that time I have accumulated a bit more than 80,000 karma. So I was just wondering, how much karma is considered a lot? 4 cat attack my cat decided to jump out from underneath a chair and attack me he barely even scratched me but my cat is annoying his name is Eddy/Edmond he's always surprising us because most of the time he's super friendly fun times 5 The first YouTube video was made closer to 1989 than it was to today Look at the months. It has been 15 years and 5 months since the video was made, and back then the video was made 15 years and 4 months away from December of 1989 6 Why do Chinese people speak Chinese when it is very difficult? They should just learn and easier language like English or Spanish. They speak like 8 languages in China but I won't list them. Edit : actually they speak a lot more. 7 Ok who should I draw a portrait of I'm bored and need inspiration so yeah. Idk, ig I'll pick my favorite and draw that 8 Can you recommend me any music to listen to So I'm bored and can't fall asleep do you guys know any good songs, bands? 9 I tried saying can i get 1mil subs for no reason and got a lot of hate, boy it’s a joke https://youtu.be/exobRyhH5fg 10 Are you guys allowed to switch off your cameras during online class? Because I'm not Maybe it's an American thing idk 11 To anyone here who is worried about college remember one thing If Kaitlyn Bennett can get through college you can too 12 I finally did it!! After a year with my Learner's Permit, I finally took the Driver's License test today and passed!! 13 Reddit costs $1.8 billion If we raise the money we can buy Reddit to make things crash quicker Please spread the news 14 God the princess and the frog is such an underrated Disney princess movie Probably my favorite Disney princess movies 15 If you want to feel wanted by someone Just rob a bankkkk, now the whole police will be looking for you. Works everytime. 16 why are you all so depressed Stop being depressed just be hapy 17 Draw with me part 2 [https://r7.whiteboardfox.com/7691988-9928-1785](https://r7.whiteboardfox.com/7691988-9928-1785) 18 Why do people hate British uniforms? They all look so pretty, I don't understand why people think that they're ugly. 19 How do i join minecraft serves through my ps4? I recently bought minecraft so don't know Also is ps plus necessary? 20 I got an A for writing an essay on a book I didn't read. It was an in clas write so I only had 55 minutes to do it. 21 Yo let's chat, hmu if you are interested Tryna make some friiiieeeennndddsssssssssssssssssssssssssss Also I'm bored 22 Why does the thought of dieing make me hapy?I have a pllan. it's going to happen. If i wasn't waiting on something I would go right now. Why do these thoughts excite me? 23 i'm still alive, but I'm deleting my Reddit tomorrowthanks for all the kind messages and all, but this place is too fucking toxic to continue being here. if u wanna talk to me, I have discord: aquamarine#3232 24 Writing something positive about my day, day #261 I slept for a while the night before so I wasn’t as tired today 25 Fun Fact: You are never not using your skeleton # # # # # # # # # # # # # # # # # # # # # # # 26 It’s not even 5 yet and it’s dark outside WHYYYYYY This is getting ridiculous. The sun needs to stop slacking. 27 I am listening to songs..... SDCARD/Music/Hans Zimmer/Inception/Mombasa.wav With Surround Sound ON on SoundAlive 28 Is it just me... That has thoughts about cringy/embarrassing alternate scenarios that almost hapened in your life? 29 Name Your Mood And I’ll Recommend A Song Will try to pick a song that you will enjoy based on your mood. Enjoy :) 30 Whats a #song you can recommend to everyone No matter what #genre they like, what song can you recommend to everyone? 31 How do I change my iOS 14 app logos to my own photos? I’m being honestly I do not know how to change my app logos #heeelllllppppp 32 Spicy fried chicken &gt;&gt;&gt;&gt;&gt; the spice, the tender meat, the aroma everything about it is just so good 33 S.T.A.L.K.E.R., Metro, or Fallout? I just want to hear your opiniuns on the games. 34 Funniest comment gets free “helpful” award because I really need to laugh... E 35 Lalalalalalalalalalalalalalalalalalalalalalala BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRB 36 I dont like emojis But i can make exceptions for this ones 🚹🕎🔯♻️🧼 37 WILLIAMS' GOT AN INVESTMENT!! I don't know about investments but GO WILLIAMS GO. 38 u/coolstarfish55 is my favorite redditor u/coolstarfish55 is my favorite redditor 39 Now I'll be the best user of teenagers And my competitors will be turned to stone 40 methodsjust a purely theoretic discussion about the easiest ways out. what would be your prefered way? with the least impact to your family and least destruction of body? 41 Sleeping pillsHow to kill myself most effectively using sleeping pills and alcohol (like vodka)? I don't want to end up being a vegetable. Only that holds me back, that's why I'm asking you my friends. 42 someone please, please tell me not toim not a good person and i want it to stop i want itt o stop so b ad but i'm scared of what would happen but i just want it over i don't know what to do. i hurt my friends and t hey stalked me but it was my fault in the first plae c and all they saw was lies lies lies lies lies . about Them i don't think g-d wants me here anymore. i think im supposed to be gone 43 Have 60 - 1mg Xanax. Thinking about taking them all. Don't know why I'm even postingIt's all too much. It hurts everyday. My sleep is only when I have peace. I just want that forever. 44 Day one of posting until something interesting happens Qwertyyiopasdfghjklzxcvbnm 45 Guess who can't sleep again How am I supposed to die in my sleep if I can't sleep? 46 I don't think I'll do itIt's awfully temping though. Just going through a rough patch 47 I see no reason to be here, no one actually loves, everyone is just faking caring about me.No one actually cares to listen and understand me. Im at fault of everything, nothing is reversable. Nothing makes me happy absolutely nothing. I have a plan to go outside the city and hang myself on a tree. I even picked a specific tree, its easy to climb has a place to tie a rope, and thick enough to hold my weight. 48 I have very few reasons left to be here. Here's some to not.1) My year and a half long relationship just ended 2) People.think im taking/lying about being suicidal. 3) Family is splitting up 4) Sexual assault 5) School sucks If anyone can talk?? At all??? Im so close. I want it to either go away or I'll make it go away. I'm in therapy. On meds (kinda) gone to my last resorts a few times (police and hospital) 49 I FINALLY TOLD MY CRUSH I LIKED HIM AND HE LIKES ME BACK!!! IM SUPER HAPPY :DDDDDD"

### b. Remove Punctuation/ Unicode characters/ Special Characters

Before processing the text, we must remove the extra, non-semantic and **non-informative characters** in the sentence. These characters are digits, white spaces, and others non-informative characters like {, }, =, @, &, %, $, ^, <, >, !, ?, ;, \n, \t, (, .

we done the following steps in this section of data cleaning 
- unicode characters
- remove URLs 
- remove HTML tags
- unwanted digits
- spacial caracters and Punctuations

1. unicode characters

In [5]:
clean_data = clean_data.encode("ascii", "ignore") 
clean_data = clean_data.decode()

clean_data

" 0 0 my teachers seeing me submit my assignment at 3am again:  i wonder if my teachers are silently judging me :/ &amp;#x200B; filler filter flicker snicker bicker clicker 1 My uncle just got married. My uncle just got married to a beautiful wife and I would like to present him with something. I couldnt think of anything else but to tell you guys. Congratulations Uncle Jeremy! Im so happy for you! 2 This is sad. The story of this girls break up. https://www.reddit.com/r/Advice/comments/jco47r/im_only_13_and_im_being_stressed_over_some_stupid/?utm_medium=android_app&amp;utm_source=share I dont need any karma, go and suport her. 3 How much reddit karma is considered a lot? Two days ago marked my 1 year anniversary of being on reddit. And in that time I have accumulated a bit more than 80,000 karma. So I was just wondering, how much karma is considered a lot? 4 cat attack my cat decided to jump out from underneath a chair and attack me he barely even scratched me but my cat is annoying his name is Eddy/Edmond he's always surprising us because most of the time he's super friendly fun times 5 The first YouTube video was made closer to 1989 than it was to today Look at the months. It has been 15 years and 5 months since the video was made, and back then the video was made 15 years and 4 months away from December of 1989 6 Why do Chinese people speak Chinese when it is very difficult? They should just learn and easier language like English or Spanish. They speak like 8 languages in China but I won't list them. Edit : actually they speak a lot more. 7 Ok who should I draw a portrait of I'm bored and need inspiration so yeah. Idk, ig I'll pick my favorite and draw that 8 Can you recommend me any music to listen to So I'm bored and can't fall asleep do you guys know any good songs, bands? 9 I tried saying can i get 1mil subs for no reason and got a lot of hate, boy its a joke https://youtu.be/exobRyhH5fg 10 Are you guys allowed to switch off your cameras during online class? Because I'm not Maybe it's an American thing idk 11 To anyone here who is worried about college remember one thing If Kaitlyn Bennett can get through college you can too 12 I finally did it!! After a year with my Learner's Permit, I finally took the Driver's License test today and passed!! 13 Reddit costs $1.8 billion If we raise the money we can buy Reddit to make things crash quicker Please spread the news 14 God the princess and the frog is such an underrated Disney princess movie Probably my favorite Disney princess movies 15 If you want to feel wanted by someone Just rob a bankkkk, now the whole police will be looking for you. Works everytime. 16 why are you all so depressed Stop being depressed just be hapy 17 Draw with me part 2 [https://r7.whiteboardfox.com/7691988-9928-1785](https://r7.whiteboardfox.com/7691988-9928-1785) 18 Why do people hate British uniforms? They all look so pretty, I don't understand why people think that they're ugly. 19 How do i join minecraft serves through my ps4? I recently bought minecraft so don't know Also is ps plus necessary? 20 I got an A for writing an essay on a book I didn't read. It was an in clas write so I only had 55 minutes to do it. 21 Yo let's chat, hmu if you are interested Tryna make some friiiieeeennndddsssssssssssssssssssssssssss Also I'm bored 22 Why does the thought of dieing make me hapy?I have a pllan. it's going to happen. If i wasn't waiting on something I would go right now. Why do these thoughts excite me? 23 i'm still alive, but I'm deleting my Reddit tomorrowthanks for all the kind messages and all, but this place is too fucking toxic to continue being here. if u wanna talk to me, I have discord: aquamarine#3232 24 Writing something positive about my day, day #261 I slept for a while the night before so I wasnt as tired today 25 Fun Fact: You are never not using your skeleton # # # # # # # # # # # # # # # # # # # # # # # 26 Its not even 5 yet and its dark outside WHYYYYYY This is getting ridiculous. The sun needs to stop slacking. 27 I am listening to songs..... SDCARD/Music/Hans Zimmer/Inception/Mombasa.wav With Surround Sound ON on SoundAlive 28 Is it just me... That has thoughts about cringy/embarrassing alternate scenarios that almost hapened in your life? 29 Name Your Mood And Ill Recommend A Song Will try to pick a song that you will enjoy based on your mood. Enjoy :) 30 Whats a #song you can recommend to everyone No matter what #genre they like, what song can you recommend to everyone? 31 How do I change my iOS 14 app logos to my own photos? Im being honestly I do not know how to change my app logos #heeelllllppppp 32 Spicy fried chicken &gt;&gt;&gt;&gt;&gt; the spice, the tender meat, the aroma everything about it is just so good 33 S.T.A.L.K.E.R., Metro, or Fallout? I just want to hear your opiniuns on the games. 34 Funniest comment gets free helpful award because I really need to laugh... E 35 Lalalalalalalalalalalalalalalalalalalalalalala BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRB 36 I dont like emojis But i can make exceptions for this ones  37 WILLIAMS' GOT AN INVESTMENT!! I don't know about investments but GO WILLIAMS GO. 38 u/coolstarfish55 is my favorite redditor u/coolstarfish55 is my favorite redditor 39 Now I'll be the best user of teenagers And my competitors will be turned to stone 40 methodsjust a purely theoretic discussion about the easiest ways out. what would be your prefered way? with the least impact to your family and least destruction of body? 41 Sleeping pillsHow to kill myself most effectively using sleeping pills and alcohol (like vodka)? I don't want to end up being a vegetable. Only that holds me back, that's why I'm asking you my friends. 42 someone please, please tell me not toim not a good person and i want it to stop i want itt o stop so b ad but i'm scared of what would happen but i just want it over i don't know what to do. i hurt my friends and t hey stalked me but it was my fault in the first plae c and all they saw was lies lies lies lies lies . about Them i don't think g-d wants me here anymore. i think im supposed to be gone 43 Have 60 - 1mg Xanax. Thinking about taking them all. Don't know why I'm even postingIt's all too much. It hurts everyday. My sleep is only when I have peace. I just want that forever. 44 Day one of posting until something interesting happens Qwertyyiopasdfghjklzxcvbnm 45 Guess who can't sleep again How am I supposed to die in my sleep if I can't sleep? 46 I don't think I'll do itIt's awfully temping though. Just going through a rough patch 47 I see no reason to be here, no one actually loves, everyone is just faking caring about me.No one actually cares to listen and understand me. Im at fault of everything, nothing is reversable. Nothing makes me happy absolutely nothing. I have a plan to go outside the city and hang myself on a tree. I even picked a specific tree, its easy to climb has a place to tie a rope, and thick enough to hold my weight. 48 I have very few reasons left to be here. Here's some to not.1) My year and a half long relationship just ended 2) People.think im taking/lying about being suicidal. 3) Family is splitting up 4) Sexual assault 5) School sucks If anyone can talk?? At all??? Im so close. I want it to either go away or I'll make it go away. I'm in therapy. On meds (kinda) gone to my last resorts a few times (police and hospital) 49 I FINALLY TOLD MY CRUSH I LIKED HIM AND HE LIKES ME BACK!!! IM SUPER HAPPY :DDDDDD"

f. remove URLs

In [6]:
clean_data = re.sub(r'https?://[a-zA-Z0-9\.\/\-_?=;&]*', '', clean_data)
clean_data

" 0 0 my teachers seeing me submit my assignment at 3am again:  i wonder if my teachers are silently judging me :/ &amp;#x200B; filler filter flicker snicker bicker clicker 1 My uncle just got married. My uncle just got married to a beautiful wife and I would like to present him with something. I couldnt think of anything else but to tell you guys. Congratulations Uncle Jeremy! Im so happy for you! 2 This is sad. The story of this girls break up.  I dont need any karma, go and suport her. 3 How much reddit karma is considered a lot? Two days ago marked my 1 year anniversary of being on reddit. And in that time I have accumulated a bit more than 80,000 karma. So I was just wondering, how much karma is considered a lot? 4 cat attack my cat decided to jump out from underneath a chair and attack me he barely even scratched me but my cat is annoying his name is Eddy/Edmond he's always surprising us because most of the time he's super friendly fun times 5 The first YouTube video was made closer to 1989 than it was to today Look at the months. It has been 15 years and 5 months since the video was made, and back then the video was made 15 years and 4 months away from December of 1989 6 Why do Chinese people speak Chinese when it is very difficult? They should just learn and easier language like English or Spanish. They speak like 8 languages in China but I won't list them. Edit : actually they speak a lot more. 7 Ok who should I draw a portrait of I'm bored and need inspiration so yeah. Idk, ig I'll pick my favorite and draw that 8 Can you recommend me any music to listen to So I'm bored and can't fall asleep do you guys know any good songs, bands? 9 I tried saying can i get 1mil subs for no reason and got a lot of hate, boy its a joke  10 Are you guys allowed to switch off your cameras during online class? Because I'm not Maybe it's an American thing idk 11 To anyone here who is worried about college remember one thing If Kaitlyn Bennett can get through college you can too 12 I finally did it!! After a year with my Learner's Permit, I finally took the Driver's License test today and passed!! 13 Reddit costs $1.8 billion If we raise the money we can buy Reddit to make things crash quicker Please spread the news 14 God the princess and the frog is such an underrated Disney princess movie Probably my favorite Disney princess movies 15 If you want to feel wanted by someone Just rob a bankkkk, now the whole police will be looking for you. Works everytime. 16 why are you all so depressed Stop being depressed just be hapy 17 Draw with me part 2 []() 18 Why do people hate British uniforms? They all look so pretty, I don't understand why people think that they're ugly. 19 How do i join minecraft serves through my ps4? I recently bought minecraft so don't know Also is ps plus necessary? 20 I got an A for writing an essay on a book I didn't read. It was an in clas write so I only had 55 minutes to do it. 21 Yo let's chat, hmu if you are interested Tryna make some friiiieeeennndddsssssssssssssssssssssssssss Also I'm bored 22 Why does the thought of dieing make me hapy?I have a pllan. it's going to happen. If i wasn't waiting on something I would go right now. Why do these thoughts excite me? 23 i'm still alive, but I'm deleting my Reddit tomorrowthanks for all the kind messages and all, but this place is too fucking toxic to continue being here. if u wanna talk to me, I have discord: aquamarine#3232 24 Writing something positive about my day, day #261 I slept for a while the night before so I wasnt as tired today 25 Fun Fact: You are never not using your skeleton # # # # # # # # # # # # # # # # # # # # # # # 26 Its not even 5 yet and its dark outside WHYYYYYY This is getting ridiculous. The sun needs to stop slacking. 27 I am listening to songs..... SDCARD/Music/Hans Zimmer/Inception/Mombasa.wav With Surround Sound ON on SoundAlive 28 Is it just me... That has thoughts about cringy/embarrassing alternate scenarios that almost hapened in your life? 29 Name Your Mood And Ill Recommend A Song Will try to pick a song that you will enjoy based on your mood. Enjoy :) 30 Whats a #song you can recommend to everyone No matter what #genre they like, what song can you recommend to everyone? 31 How do I change my iOS 14 app logos to my own photos? Im being honestly I do not know how to change my app logos #heeelllllppppp 32 Spicy fried chicken &gt;&gt;&gt;&gt;&gt; the spice, the tender meat, the aroma everything about it is just so good 33 S.T.A.L.K.E.R., Metro, or Fallout? I just want to hear your opiniuns on the games. 34 Funniest comment gets free helpful award because I really need to laugh... E 35 Lalalalalalalalalalalalalalalalalalalalalalala BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRB 36 I dont like emojis But i can make exceptions for this ones  37 WILLIAMS' GOT AN INVESTMENT!! I don't know about investments but GO WILLIAMS GO. 38 u/coolstarfish55 is my favorite redditor u/coolstarfish55 is my favorite redditor 39 Now I'll be the best user of teenagers And my competitors will be turned to stone 40 methodsjust a purely theoretic discussion about the easiest ways out. what would be your prefered way? with the least impact to your family and least destruction of body? 41 Sleeping pillsHow to kill myself most effectively using sleeping pills and alcohol (like vodka)? I don't want to end up being a vegetable. Only that holds me back, that's why I'm asking you my friends. 42 someone please, please tell me not toim not a good person and i want it to stop i want itt o stop so b ad but i'm scared of what would happen but i just want it over i don't know what to do. i hurt my friends and t hey stalked me but it was my fault in the first plae c and all they saw was lies lies lies lies lies . about Them i don't think g-d wants me here anymore. i think im supposed to be gone 43 Have 60 - 1mg Xanax. Thinking about taking them all. Don't know why I'm even postingIt's all too much. It hurts everyday. My sleep is only when I have peace. I just want that forever. 44 Day one of posting until something interesting happens Qwertyyiopasdfghjklzxcvbnm 45 Guess who can't sleep again How am I supposed to die in my sleep if I can't sleep? 46 I don't think I'll do itIt's awfully temping though. Just going through a rough patch 47 I see no reason to be here, no one actually loves, everyone is just faking caring about me.No one actually cares to listen and understand me. Im at fault of everything, nothing is reversable. Nothing makes me happy absolutely nothing. I have a plan to go outside the city and hang myself on a tree. I even picked a specific tree, its easy to climb has a place to tie a rope, and thick enough to hold my weight. 48 I have very few reasons left to be here. Here's some to not.1) My year and a half long relationship just ended 2) People.think im taking/lying about being suicidal. 3) Family is splitting up 4) Sexual assault 5) School sucks If anyone can talk?? At all??? Im so close. I want it to either go away or I'll make it go away. I'm in therapy. On meds (kinda) gone to my last resorts a few times (police and hospital) 49 I FINALLY TOLD MY CRUSH I LIKED HIM AND HE LIKES ME BACK!!! IM SUPER HAPPY :DDDDDD"

g. remove HTML tags

In [7]:
clean_data = re.sub(r'<[^>]+>', '', clean_data)
clean_data

" 0 0 my teachers seeing me submit my assignment at 3am again:  i wonder if my teachers are silently judging me :/ &amp;#x200B; filler filter flicker snicker bicker clicker 1 My uncle just got married. My uncle just got married to a beautiful wife and I would like to present him with something. I couldnt think of anything else but to tell you guys. Congratulations Uncle Jeremy! Im so happy for you! 2 This is sad. The story of this girls break up.  I dont need any karma, go and suport her. 3 How much reddit karma is considered a lot? Two days ago marked my 1 year anniversary of being on reddit. And in that time I have accumulated a bit more than 80,000 karma. So I was just wondering, how much karma is considered a lot? 4 cat attack my cat decided to jump out from underneath a chair and attack me he barely even scratched me but my cat is annoying his name is Eddy/Edmond he's always surprising us because most of the time he's super friendly fun times 5 The first YouTube video was made closer to 1989 than it was to today Look at the months. It has been 15 years and 5 months since the video was made, and back then the video was made 15 years and 4 months away from December of 1989 6 Why do Chinese people speak Chinese when it is very difficult? They should just learn and easier language like English or Spanish. They speak like 8 languages in China but I won't list them. Edit : actually they speak a lot more. 7 Ok who should I draw a portrait of I'm bored and need inspiration so yeah. Idk, ig I'll pick my favorite and draw that 8 Can you recommend me any music to listen to So I'm bored and can't fall asleep do you guys know any good songs, bands? 9 I tried saying can i get 1mil subs for no reason and got a lot of hate, boy its a joke  10 Are you guys allowed to switch off your cameras during online class? Because I'm not Maybe it's an American thing idk 11 To anyone here who is worried about college remember one thing If Kaitlyn Bennett can get through college you can too 12 I finally did it!! After a year with my Learner's Permit, I finally took the Driver's License test today and passed!! 13 Reddit costs $1.8 billion If we raise the money we can buy Reddit to make things crash quicker Please spread the news 14 God the princess and the frog is such an underrated Disney princess movie Probably my favorite Disney princess movies 15 If you want to feel wanted by someone Just rob a bankkkk, now the whole police will be looking for you. Works everytime. 16 why are you all so depressed Stop being depressed just be hapy 17 Draw with me part 2 []() 18 Why do people hate British uniforms? They all look so pretty, I don't understand why people think that they're ugly. 19 How do i join minecraft serves through my ps4? I recently bought minecraft so don't know Also is ps plus necessary? 20 I got an A for writing an essay on a book I didn't read. It was an in clas write so I only had 55 minutes to do it. 21 Yo let's chat, hmu if you are interested Tryna make some friiiieeeennndddsssssssssssssssssssssssssss Also I'm bored 22 Why does the thought of dieing make me hapy?I have a pllan. it's going to happen. If i wasn't waiting on something I would go right now. Why do these thoughts excite me? 23 i'm still alive, but I'm deleting my Reddit tomorrowthanks for all the kind messages and all, but this place is too fucking toxic to continue being here. if u wanna talk to me, I have discord: aquamarine#3232 24 Writing something positive about my day, day #261 I slept for a while the night before so I wasnt as tired today 25 Fun Fact: You are never not using your skeleton # # # # # # # # # # # # # # # # # # # # # # # 26 Its not even 5 yet and its dark outside WHYYYYYY This is getting ridiculous. The sun needs to stop slacking. 27 I am listening to songs..... SDCARD/Music/Hans Zimmer/Inception/Mombasa.wav With Surround Sound ON on SoundAlive 28 Is it just me... That has thoughts about cringy/embarrassing alternate scenarios that almost hapened in your life? 29 Name Your Mood And Ill Recommend A Song Will try to pick a song that you will enjoy based on your mood. Enjoy :) 30 Whats a #song you can recommend to everyone No matter what #genre they like, what song can you recommend to everyone? 31 How do I change my iOS 14 app logos to my own photos? Im being honestly I do not know how to change my app logos #heeelllllppppp 32 Spicy fried chicken &gt;&gt;&gt;&gt;&gt; the spice, the tender meat, the aroma everything about it is just so good 33 S.T.A.L.K.E.R., Metro, or Fallout? I just want to hear your opiniuns on the games. 34 Funniest comment gets free helpful award because I really need to laugh... E 35 Lalalalalalalalalalalalalalalalalalalalalalala BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRB 36 I dont like emojis But i can make exceptions for this ones  37 WILLIAMS' GOT AN INVESTMENT!! I don't know about investments but GO WILLIAMS GO. 38 u/coolstarfish55 is my favorite redditor u/coolstarfish55 is my favorite redditor 39 Now I'll be the best user of teenagers And my competitors will be turned to stone 40 methodsjust a purely theoretic discussion about the easiest ways out. what would be your prefered way? with the least impact to your family and least destruction of body? 41 Sleeping pillsHow to kill myself most effectively using sleeping pills and alcohol (like vodka)? I don't want to end up being a vegetable. Only that holds me back, that's why I'm asking you my friends. 42 someone please, please tell me not toim not a good person and i want it to stop i want itt o stop so b ad but i'm scared of what would happen but i just want it over i don't know what to do. i hurt my friends and t hey stalked me but it was my fault in the first plae c and all they saw was lies lies lies lies lies . about Them i don't think g-d wants me here anymore. i think im supposed to be gone 43 Have 60 - 1mg Xanax. Thinking about taking them all. Don't know why I'm even postingIt's all too much. It hurts everyday. My sleep is only when I have peace. I just want that forever. 44 Day one of posting until something interesting happens Qwertyyiopasdfghjklzxcvbnm 45 Guess who can't sleep again How am I supposed to die in my sleep if I can't sleep? 46 I don't think I'll do itIt's awfully temping though. Just going through a rough patch 47 I see no reason to be here, no one actually loves, everyone is just faking caring about me.No one actually cares to listen and understand me. Im at fault of everything, nothing is reversable. Nothing makes me happy absolutely nothing. I have a plan to go outside the city and hang myself on a tree. I even picked a specific tree, its easy to climb has a place to tie a rope, and thick enough to hold my weight. 48 I have very few reasons left to be here. Here's some to not.1) My year and a half long relationship just ended 2) People.think im taking/lying about being suicidal. 3) Family is splitting up 4) Sexual assault 5) School sucks If anyone can talk?? At all??? Im so close. I want it to either go away or I'll make it go away. I'm in therapy. On meds (kinda) gone to my last resorts a few times (police and hospital) 49 I FINALLY TOLD MY CRUSH I LIKED HIM AND HE LIKES ME BACK!!! IM SUPER HAPPY :DDDDDD"

2. unwanted digits

In [8]:
unwanted_digit = ['0','1','2','3','4','5','6','7','8','9']

for digit in unwanted_digit:
    clean_data = clean_data.replace(digit, "")

3. spacial caracters and Punctuations

In [9]:
unwanted_punc = ['"',"'",'=','@','&','%','.',',',':','\\','$','^','<','>','!','?','{','}',';','\n','\t','(',')','[',']','/','*','+','#','\u200c','\ufeff','-','_','|']

for punc in unwanted_punc:
    clean_data = clean_data.replace(punc, "")

### c. Hashtag removes

In [10]:
clean_data = clean_data.replace("#", "")

### d. Tokenization

One of the most important steps in processing natural languages ​​is the tokenization step, in which we separate the sentence or corpus into its component or tokens words.

- In this section, we used the **NLTK** library in Python to implement tokenization.
- An elementary and very simple method to extract the words of a sentence is to use spaces and separate the words, although, of course, in languages ​​such as Japanese where there are no spaces, we use other methods such as the Maximum Matching algorithm.

In [11]:
from nltk.tokenize import word_tokenize

tokens = word_tokenize(clean_data)
print(tokens, len(tokens))

['my', 'teachers', 'seeing', 'me', 'submit', 'my', 'assignment', 'at', 'am', 'again', 'i', 'wonder', 'if', 'my', 'teachers', 'are', 'silently', 'judging', 'me', 'ampxB', 'filler', 'filter', 'flicker', 'snicker', 'bicker', 'clicker', 'My', 'uncle', 'just', 'got', 'married', 'My', 'uncle', 'just', 'got', 'married', 'to', 'a', 'beautiful', 'wife', 'and', 'I', 'would', 'like', 'to', 'present', 'him', 'with', 'something', 'I', 'couldnt', 'think', 'of', 'anything', 'else', 'but', 'to', 'tell', 'you', 'guys', 'Congratulations', 'Uncle', 'Jeremy', 'Im', 'so', 'happy', 'for', 'you', 'This', 'is', 'sad', 'The', 'story', 'of', 'this', 'girls', 'break', 'up', 'I', 'dont', 'need', 'any', 'karma', 'go', 'and', 'suport', 'her', 'How', 'much', 'reddit', 'karma', 'is', 'considered', 'a', 'lot', 'Two', 'days', 'ago', 'marked', 'my', 'year', 'anniversary', 'of', 'being', 'on', 'reddit', 'And', 'in', 'that', 'time', 'I', 'have', 'accumulated', 'a', 'bit', 'more', 'than', 'karma', 'So', 'I', 'was', 'just', 'wondering', 'how', 'much', 'karma', 'is', 'considered', 'a', 'lot', 'cat', 'attack', 'my', 'cat', 'decided', 'to', 'jump', 'out', 'from', 'underneath', 'a', 'chair', 'and', 'attack', 'me', 'he', 'barely', 'even', 'scratched', 'me', 'but', 'my', 'cat', 'is', 'annoying', 'his', 'name', 'is', 'EddyEdmond', 'hes', 'always', 'surprising', 'us', 'because', 'most', 'of', 'the', 'time', 'hes', 'super', 'friendly', 'fun', 'times', 'The', 'first', 'YouTube', 'video', 'was', 'made', 'closer', 'to', 'than', 'it', 'was', 'to', 'today', 'Look', 'at', 'the', 'months', 'It', 'has', 'been', 'years', 'and', 'months', 'since', 'the', 'video', 'was', 'made', 'and', 'back', 'then', 'the', 'video', 'was', 'made', 'years', 'and', 'months', 'away', 'from', 'December', 'of', 'Why', 'do', 'Chinese', 'people', 'speak', 'Chinese', 'when', 'it', 'is', 'very', 'difficult', 'They', 'should', 'just', 'learn', 'and', 'easier', 'language', 'like', 'English', 'or', 'Spanish', 'They', 'speak', 'like', 'languages', 'in', 'China', 'but', 'I', 'wont', 'list', 'them', 'Edit', 'actually', 'they', 'speak', 'a', 'lot', 'more', 'Ok', 'who', 'should', 'I', 'draw', 'a', 'portrait', 'of', 'Im', 'bored', 'and', 'need', 'inspiration', 'so', 'yeah', 'Idk', 'ig', 'Ill', 'pick', 'my', 'favorite', 'and', 'draw', 'that', 'Can', 'you', 'recommend', 'me', 'any', 'music', 'to', 'listen', 'to', 'So', 'Im', 'bored', 'and', 'cant', 'fall', 'asleep', 'do', 'you', 'guys', 'know', 'any', 'good', 'songs', 'bands', 'I', 'tried', 'saying', 'can', 'i', 'get', 'mil', 'subs', 'for', 'no', 'reason', 'and', 'got', 'a', 'lot', 'of', 'hate', 'boy', 'its', 'a', 'joke', 'Are', 'you', 'guys', 'allowed', 'to', 'switch', 'off', 'your', 'cameras', 'during', 'online', 'class', 'Because', 'Im', 'not', 'Maybe', 'its', 'an', 'American', 'thing', 'idk', 'To', 'anyone', 'here', 'who', 'is', 'worried', 'about', 'college', 'remember', 'one', 'thing', 'If', 'Kaitlyn', 'Bennett', 'can', 'get', 'through', 'college', 'you', 'can', 'too', 'I', 'finally', 'did', 'it', 'After', 'a', 'year', 'with', 'my', 'Learners', 'Permit', 'I', 'finally', 'took', 'the', 'Drivers', 'License', 'test', 'today', 'and', 'passed', 'Reddit', 'costs', 'billion', 'If', 'we', 'raise', 'the', 'money', 'we', 'can', 'buy', 'Reddit', 'to', 'make', 'things', 'crash', 'quicker', 'Please', 'spread', 'the', 'news', 'God', 'the', 'princess', 'and', 'the', 'frog', 'is', 'such', 'an', 'underrated', 'Disney', 'princess', 'movie', 'Probably', 'my', 'favorite', 'Disney', 'princess', 'movies', 'If', 'you', 'want', 'to', 'feel', 'wanted', 'by', 'someone', 'Just', 'rob', 'a', 'bankkkk', 'now', 'the', 'whole', 'police', 'will', 'be', 'looking', 'for', 'you', 'Works', 'everytime', 'why', 'are', 'you', 'all', 'so', 'depressed', 'Stop', 'being', 'depressed', 'just', 'be', 'hapy', 'Draw', 'with', 'me', 'part', 'Why', 'do', 'people', 'hate', 'British', 'uniforms', 'They', 'all', 'look', 'so', 'pretty', 'I', 'dont', 'understand', 'why', 'people', 'think', 'that', 'theyre', 'ugly', 'How', 'do', 'i', 'join', 'minecraft', 'serves', 'through', 'my', 'ps', 'I', 'recently', 'bought', 'minecraft', 'so', 'dont', 'know', 'Also', 'is', 'ps', 'plus', 'necessary', 'I', 'got', 'an', 'A', 'for', 'writing', 'an', 'essay', 'on', 'a', 'book', 'I', 'didnt', 'read', 'It', 'was', 'an', 'in', 'clas', 'write', 'so', 'I', 'only', 'had', 'minutes', 'to', 'do', 'it', 'Yo', 'lets', 'chat', 'hmu', 'if', 'you', 'are', 'interested', 'Tryna', 'make', 'some', 'friiiieeeennndddsssssssssssssssssssssssssss', 'Also', 'Im', 'bored', 'Why', 'does', 'the', 'thought', 'of', 'dieing', 'make', 'me', 'hapyI', 'have', 'a', 'pllan', 'its', 'going', 'to', 'happen', 'If', 'i', 'wasnt', 'waiting', 'on', 'something', 'I', 'would', 'go', 'right', 'now', 'Why', 'do', 'these', 'thoughts', 'excite', 'me', 'im', 'still', 'alive', 'but', 'Im', 'deleting', 'my', 'Reddit', 'tomorrowthanks', 'for', 'all', 'the', 'kind', 'messages', 'and', 'all', 'but', 'this', 'place', 'is', 'too', 'fucking', 'toxic', 'to', 'continue', 'being', 'here', 'if', 'u', 'wan', 'na', 'talk', 'to', 'me', 'I', 'have', 'discord', 'aquamarine', 'Writing', 'something', 'positive', 'about', 'my', 'day', 'day', 'I', 'slept', 'for', 'a', 'while', 'the', 'night', 'before', 'so', 'I', 'wasnt', 'as', 'tired', 'today', 'Fun', 'Fact', 'You', 'are', 'never', 'not', 'using', 'your', 'skeleton', 'Its', 'not', 'even', 'yet', 'and', 'its', 'dark', 'outside', 'WHYYYYYY', 'This', 'is', 'getting', 'ridiculous', 'The', 'sun', 'needs', 'to', 'stop', 'slacking', 'I', 'am', 'listening', 'to', 'songs', 'SDCARDMusicHans', 'ZimmerInceptionMombasawav', 'With', 'Surround', 'Sound', 'ON', 'on', 'SoundAlive', 'Is', 'it', 'just', 'me', 'That', 'has', 'thoughts', 'about', 'cringyembarrassing', 'alternate', 'scenarios', 'that', 'almost', 'hapened', 'in', 'your', 'life', 'Name', 'Your', 'Mood', 'And', 'Ill', 'Recommend', 'A', 'Song', 'Will', 'try', 'to', 'pick', 'a', 'song', 'that', 'you', 'will', 'enjoy', 'based', 'on', 'your', 'mood', 'Enjoy', 'Whats', 'a', 'song', 'you', 'can', 'recommend', 'to', 'everyone', 'No', 'matter', 'what', 'genre', 'they', 'like', 'what', 'song', 'can', 'you', 'recommend', 'to', 'everyone', 'How', 'do', 'I', 'change', 'my', 'iOS', 'app', 'logos', 'to', 'my', 'own', 'photos', 'Im', 'being', 'honestly', 'I', 'do', 'not', 'know', 'how', 'to', 'change', 'my', 'app', 'logos', 'heeelllllppppp', 'Spicy', 'fried', 'chicken', 'gtgtgtgtgt', 'the', 'spice', 'the', 'tender', 'meat', 'the', 'aroma', 'everything', 'about', 'it', 'is', 'just', 'so', 'good', 'STALKER', 'Metro', 'or', 'Fallout', 'I', 'just', 'want', 'to', 'hear', 'your', 'opiniuns', 'on', 'the', 'games', 'Funniest', 'comment', 'gets', 'free', 'helpful', 'award', 'because', 'I', 'really', 'need', 'to', 'laugh', 'E', 'Lalalalalalalalalalalalalalalalalalalalalalala', 'BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRB', 'I', 'dont', 'like', 'emojis', 'But', 'i', 'can', 'make', 'exceptions', 'for', 'this', 'ones', 'WILLIAMS', 'GOT', 'AN', 'INVESTMENT', 'I', 'dont', 'know', 'about', 'investments', 'but', 'GO', 'WILLIAMS', 'GO', 'ucoolstarfish', 'is', 'my', 'favorite', 'redditor', 'ucoolstarfish', 'is', 'my', 'favorite', 'redditor', 'Now', 'Ill', 'be', 'the', 'best', 'user', 'of', 'teenagers', 'And', 'my', 'competitors', 'will', 'be', 'turned', 'to', 'stone', 'methodsjust', 'a', 'purely', 'theoretic', 'discussion', 'about', 'the', 'easiest', 'ways', 'out', 'what', 'would', 'be', 'your', 'prefered', 'way', 'with', 'the', 'least', 'impact', 'to', 'your', 'family', 'and', 'least', 'destruction', 'of', 'body', 'Sleeping', 'pillsHow', 'to', 'kill', 'myself', 'most', 'effectively', 'using', 'sleeping', 'pills', 'and', 'alcohol', 'like', 'vodka', 'I', 'dont', 'want', 'to', 'end', 'up', 'being', 'a', 'vegetable', 'Only', 'that', 'holds', 'me', 'back', 'thats', 'why', 'Im', 'asking', 'you', 'my', 'friends', 'someone', 'please', 'please', 'tell', 'me', 'not', 'toim', 'not', 'a', 'good', 'person', 'and', 'i', 'want', 'it', 'to', 'stop', 'i', 'want', 'itt', 'o', 'stop', 'so', 'b', 'ad', 'but', 'im', 'scared', 'of', 'what', 'would', 'happen', 'but', 'i', 'just', 'want', 'it', 'over', 'i', 'dont', 'know', 'what', 'to', 'do', 'i', 'hurt', 'my', 'friends', 'and', 't', 'hey', 'stalked', 'me', 'but', 'it', 'was', 'my', 'fault', 'in', 'the', 'first', 'plae', 'c', 'and', 'all', 'they', 'saw', 'was', 'lies', 'lies', 'lies', 'lies', 'lies', 'about', 'Them', 'i', 'dont', 'think', 'gd', 'wants', 'me', 'here', 'anymore', 'i', 'think', 'im', 'supposed', 'to', 'be', 'gone', 'Have', 'mg', 'Xanax', 'Thinking', 'about', 'taking', 'them', 'all', 'Dont', 'know', 'why', 'Im', 'even', 'postingIts', 'all', 'too', 'much', 'It', 'hurts', 'everyday', 'My', 'sleep', 'is', 'only', 'when', 'I', 'have', 'peace', 'I', 'just', 'want', 'that', 'forever', 'Day', 'one', 'of', 'posting', 'until', 'something', 'interesting', 'happens', 'Qwertyyiopasdfghjklzxcvbnm', 'Guess', 'who', 'cant', 'sleep', 'again', 'How', 'am', 'I', 'supposed', 'to', 'die', 'in', 'my', 'sleep', 'if', 'I', 'cant', 'sleep', 'I', 'dont', 'think', 'Ill', 'do', 'itIts', 'awfully', 'temping', 'though', 'Just', 'going', 'through', 'a', 'rough', 'patch', 'I', 'see', 'no', 'reason', 'to', 'be', 'here', 'no', 'one', 'actually', 'loves', 'everyone', 'is', 'just', 'faking', 'caring', 'about', 'meNo', 'one', 'actually', 'cares', 'to', 'listen', 'and', 'understand', 'me', 'Im', 'at', 'fault', 'of', 'everything', 'nothing', 'is', 'reversable', 'Nothing', 'makes', 'me', 'happy', 'absolutely', 'nothing', 'I', 'have', 'a', 'plan', 'to', 'go', 'outside', 'the', 'city', 'and', 'hang', 'myself', 'on', 'a', 'tree', 'I', 'even', 'picked', 'a', 'specific', 'tree', 'its', 'easy', 'to', 'climb', 'has', 'a', 'place', 'to', 'tie', 'a', 'rope', 'and', 'thick', 'enough', 'to', 'hold', 'my', 'weight', 'I', 'have', 'very', 'few', 'reasons', 'left', 'to', 'be', 'here', 'Heres', 'some', 'to', 'not', 'My', 'year', 'and', 'a', 'half', 'long', 'relationship', 'just', 'ended', 'Peoplethink', 'im', 'takinglying', 'about', 'being', 'suicidal', 'Family', 'is', 'splitting', 'up', 'Sexual', 'assault', 'School', 'sucks', 'If', 'anyone', 'can', 'talk', 'At', 'all', 'Im', 'so', 'close', 'I', 'want', 'it', 'to', 'either', 'go', 'away', 'or', 'Ill', 'make', 'it', 'go', 'away', 'Im', 'in', 'therapy', 'On', 'meds', 'kinda', 'gone', 'to', 'my', 'last', 'resorts', 'a', 'few', 'times', 'police', 'and', 'hospital', 'I', 'FINALLY', 'TOLD', 'MY', 'CRUSH', 'I', 'LIKED', 'HIM', 'AND', 'HE', 'LIKES', 'ME', 'BACK', 'IM', 'SUPER', 'HAPPY', 'DDDDDD'] 1267

### e. Stop words

Stop words are available in abundance in any human language. By removing these words, we remove the low-level information from our text in order to give more focus to the important information.
- We have the stopwords of that language in any language, and we use the **wordnet corpus** in the ntlk library to view its list in English.

For example, let's look at 20 of the English stop words that exist in wordnet.

In [13]:
from nltk.corpus import stopwords

stopwords.words("english")[:20]

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his']

First, we extract the tokens and then **if any of these tokens are present in the list of stopwords, we remove them from the set of tokens**.

In [ ]:


# step1: tokenization
tokens = word_tokenize(clean_data)

# step2: remove capitalization tokens
normal_tokens = []
for token in tokens:
    normal_tokens.append(token.lower())


# step3: remove stopwords
clean_stop_words_tokens = []
for token in normal_tokens:
    if token not in stopwords.words("english"): 
        clean_stop_words_tokens.append(token)
print(clean_stop_words_tokens, len(clean_stop_words_tokens))

['teachers', 'seeing', 'submit', 'assignment', 'wonder', 'teachers', 'silently', 'judging', 'ampxb', 'filler', 'filter', 'flicker', 'snicker', 'bicker', 'clicker', 'uncle', 'got', 'married', 'uncle', 'got', 'married', 'beautiful', 'wife', 'would', 'like', 'present', 'something', 'couldnt', 'think', 'anything', 'else', 'tell', 'guys', 'congratulations', 'uncle', 'jeremy', 'im', 'happy', 'sad', 'story', 'girls', 'break', 'dont', 'need', 'karma', 'go', 'suport', 'much', 'reddit', 'karma', 'considered', 'lot', 'two', 'days', 'ago', 'marked', 'year', 'anniversary', 'reddit', 'time', 'accumulated', 'bit', 'karma', 'wondering', 'much', 'karma', 'considered', 'lot', 'cat', 'attack', 'cat', 'decided', 'jump', 'underneath', 'chair', 'attack', 'barely', 'even', 'scratched', 'cat', 'annoying', 'name', 'eddyedmond', 'hes', 'always', 'surprising', 'us', 'time', 'hes', 'super', 'friendly', 'fun', 'times', 'first', 'youtube', 'video', 'made', 'closer', 'today', 'look', 'months', 'years', 'months', 'since', 'video', 'made', 'back', 'video', 'made', 'years', 'months', 'away', 'december', 'chinese', 'people', 'speak', 'chinese', 'difficult', 'learn', 'easier', 'language', 'like', 'english', 'spanish', 'speak', 'like', 'languages', 'china', 'wont', 'list', 'edit', 'actually', 'speak', 'lot', 'ok', 'draw', 'portrait', 'im', 'bored', 'need', 'inspiration', 'yeah', 'idk', 'ig', 'ill', 'pick', 'favorite', 'draw', 'recommend', 'music', 'listen', 'im', 'bored', 'cant', 'fall', 'asleep', 'guys', 'know', 'good', 'songs', 'bands', 'tried', 'saying', 'get', 'mil', 'subs', 'reason', 'got', 'lot', 'hate', 'boy', 'joke', 'guys', 'allowed', 'switch', 'cameras', 'online', 'class', 'im', 'maybe', 'american', 'thing', 'idk', 'anyone', 'worried', 'college', 'remember', 'one', 'thing', 'kaitlyn', 'bennett', 'get', 'college', 'finally', 'year', 'learners', 'permit', 'finally', 'took', 'drivers', 'license', 'test', 'today', 'passed', 'reddit', 'costs', 'billion', 'raise', 'money', 'buy', 'reddit', 'make', 'things', 'crash', 'quicker', 'please', 'spread', 'news', 'god', 'princess', 'frog', 'underrated', 'disney', 'princess', 'movie', 'probably', 'favorite', 'disney', 'princess', 'movies', 'want', 'feel', 'wanted', 'someone', 'rob', 'bankkkk', 'whole', 'police', 'looking', 'works', 'everytime', 'depressed', 'stop', 'depressed', 'hapy', 'draw', 'part', 'people', 'hate', 'british', 'uniforms', 'look', 'pretty', 'dont', 'understand', 'people', 'think', 'theyre', 'ugly', 'join', 'minecraft', 'serves', 'ps', 'recently', 'bought', 'minecraft', 'dont', 'know', 'also', 'ps', 'plus', 'necessary', 'got', 'writing', 'essay', 'book', 'didnt', 'read', 'clas', 'write', 'minutes', 'yo', 'lets', 'chat', 'hmu', 'interested', 'tryna', 'make', 'friiiieeeennndddsssssssssssssssssssssssssss', 'also', 'im', 'bored', 'thought', 'dieing', 'make', 'hapyi', 'pllan', 'going', 'happen', 'wasnt', 'waiting', 'something', 'would', 'go', 'right', 'thoughts', 'excite', 'im', 'still', 'alive', 'im', 'deleting', 'reddit', 'tomorrowthanks', 'kind', 'messages', 'place', 'fucking', 'toxic', 'continue', 'u', 'wan', 'na', 'talk', 'discord', 'aquamarine', 'writing', 'something', 'positive', 'day', 'day', 'slept', 'night', 'wasnt', 'tired', 'today', 'fun', 'fact', 'never', 'using', 'skeleton', 'even', 'yet', 'dark', 'outside', 'whyyyyyy', 'getting', 'ridiculous', 'sun', 'needs', 'stop', 'slacking', 'listening', 'songs', 'sdcardmusichans', 'zimmerinceptionmombasawav', 'surround', 'sound', 'soundalive', 'thoughts', 'cringyembarrassing', 'alternate', 'scenarios', 'almost', 'hapened', 'life', 'name', 'mood', 'ill', 'recommend', 'song', 'try', 'pick', 'song', 'enjoy', 'based', 'mood', 'enjoy', 'whats', 'song', 'recommend', 'everyone', 'matter', 'genre', 'like', 'song', 'recommend', 'everyone', 'change', 'ios', 'app', 'logos', 'photos', 'im', 'honestly', 'know', 'change', 'app', 'logos', 'heeelllllppppp', 'spicy', 'fried', 'chicken', 'gtgtgtgtgt', 'spice', 'tender', 'meat', 'aroma', 'everything', 'good', 'stalker', 'metro', 'fallout', 'want', 'hear', 'opiniuns', 'games', 'funniest', 'comment', 'gets', 'free', 'helpful', 'award', 'really', 'need', 'laugh', 'e', 'lalalalalalalalalalalalalalalalalalalalalalala', 'brbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrb', 'dont', 'like', 'emojis', 'make', 'exceptions', 'ones', 'williams', 'got', 'investment', 'dont', 'know', 'investments', 'go', 'williams', 'go', 'ucoolstarfish', 'favorite', 'redditor', 'ucoolstarfish', 'favorite', 'redditor', 'ill', 'best', 'user', 'teenagers', 'competitors', 'turned', 'stone', 'methodsjust', 'purely', 'theoretic', 'discussion', 'easiest', 'ways', 'would', 'prefered', 'way', 'least', 'impact', 'family', 'least', 'destruction', 'body', 'sleeping', 'pillshow', 'kill', 'effectively', 'using', 'sleeping', 'pills', 'alcohol', 'like', 'vodka', 'dont', 'want', 'end', 'vegetable', 'holds', 'back', 'thats', 'im', 'asking', 'friends', 'someone', 'please', 'please', 'tell', 'toim', 'good', 'person', 'want', 'stop', 'want', 'itt', 'stop', 'b', 'ad', 'im', 'scared', 'would', 'happen', 'want', 'dont', 'know', 'hurt', 'friends', 'hey', 'stalked', 'fault', 'first', 'plae', 'c', 'saw', 'lies', 'lies', 'lies', 'lies', 'lies', 'dont', 'think', 'gd', 'wants', 'anymore', 'think', 'im', 'supposed', 'gone', 'mg', 'xanax', 'thinking', 'taking', 'dont', 'know', 'im', 'even', 'postingits', 'much', 'hurts', 'everyday', 'sleep', 'peace', 'want', 'forever', 'day', 'one', 'posting', 'something', 'interesting', 'happens', 'qwertyyiopasdfghjklzxcvbnm', 'guess', 'cant', 'sleep', 'supposed', 'die', 'sleep', 'cant', 'sleep', 'dont', 'think', 'ill', 'itits', 'awfully', 'temping', 'though', 'going', 'rough', 'patch', 'see', 'reason', 'one', 'actually', 'loves', 'everyone', 'faking', 'caring', 'meno', 'one', 'actually', 'cares', 'listen', 'understand', 'im', 'fault', 'everything', 'nothing', 'reversable', 'nothing', 'makes', 'happy', 'absolutely', 'nothing', 'plan', 'go', 'outside', 'city', 'hang', 'tree', 'even', 'picked', 'specific', 'tree', 'easy', 'climb', 'place', 'tie', 'rope', 'thick', 'enough', 'hold', 'weight', 'reasons', 'left', 'heres', 'year', 'half', 'long', 'relationship', 'ended', 'peoplethink', 'im', 'takinglying', 'suicidal', 'family', 'splitting', 'sexual', 'assault', 'school', 'sucks', 'anyone', 'talk', 'im', 'close', 'want', 'either', 'go', 'away', 'ill', 'make', 'go', 'away', 'im', 'therapy', 'meds', 'kinda', 'gone', 'last', 'resorts', 'times', 'police', 'hospital', 'finally', 'told', 'crush', 'liked', 'likes', 'back', 'im', 'super', 'happy', 'dddddd'] 670

### f. Remove URLs

دو مرحله پيش رو يعني حذف آدرس هاي اينترنتي و حذف تگ هاي اچ تي ام ال را پيش از اين انجام داديم با استفاده از عبارات با قاعاده در پايتون

In [16]:
clean_data = re.sub(r'^https?:\/\/.*[\r\n]*', ' ', clean_data)

### g. Remove HTML tags

In [17]:
clean_data = re.sub(r'<[^>]+>', ' ', clean_data)

### h. Repeated characters reduction, for example: Hellllo → Hello

Sometimes in social networks, some of the main characters of a word are repeated several times to emphasize more. For example, the word frrrrrieeeeeeennnddss, we must return these words to their original form and remove the repeated character.

- We wrote a class to remove repeated parameters with name **RepeatReplacer**.
- For this operation, we use the **wordnet corpus**, which is a dictionary of English words.

RepeatReplacer Class for example the word of **loooove** 
```python
step1: (loo)(o)o(ve)    => o: remove
step2: (lo)(o)o(ve)     => o: remove
step3: (l)(o)o(ve)      => o: remove
step3: love             => are on wordnet
```

In [ ]:



class RepeatReplacer():
    def __init__(self):
        # The beginning and the end char of word can be anything, but there must be a repeated character in the middle
        self.repeat_regexp = re.compile(r'(\w*)(\w)\2(\w*)') 
        self.repl = r'\1\2\3' # 1: start chars + a char, 2: middle char, 3: end chars

    def replace(self, word):
        if(wordnet.synsets(word)): 
            return word # if the word was in wordnet returns that word.
            
        repl_word = self.repeat_regexp.sub(self.repl, word) # Delete a repeated character
        if(repl_word != word): 
            return self.replace(repl_word) # Recursive function
        else: 
            return repl_word # The word is not in word net

In [20]:
replacer = RepeatReplacer()

test_token = "Hellllo"
replacer.replace(word=test_token)

'Hello'

In [21]:
replacer = RepeatReplacer()

clean_repeat_tokens = []
for token in clean_stop_words_tokens:
    clean = replacer.replace(word=token)
    clean_repeat_tokens.append(clean)
    if clean != token: print(token, "=> clean: ", clean)

print(clean_repeat_tokens, len(clean_repeat_tokens))

reddit => clean:  redit
reddit => clean:  redit
eddyedmond => clean:  edyedmond
reddit => clean:  redit
reddit => clean:  redit
bankkkk => clean:  bank
friiiieeeennndddsssssssssssssssssssssssssss => clean:  friends
pllan => clean:  plan
reddit => clean:  redit
tomorrowthanks => clean:  tomorowthanks
whyyyyyy => clean:  why
zimmerinceptionmombasawav => clean:  zimerinceptionmombasawav
cringyembarrassing => clean:  cringyembarasing
app => clean:  ap
app => clean:  ap
heeelllllppppp => clean:  help
ucoolstarfish => clean:  ucolstarfish
redditor => clean:  reditor
ucoolstarfish => clean:  ucolstarfish
redditor => clean:  reditor
pillshow => clean:  pilshow
itt => clean:  it
qwertyyiopasdfghjklzxcvbnm => clean:  qwertyiopasdfghjklzxcvbnm
dddddd => clean:  dd
['teachers', 'seeing', 'submit', 'assignment', 'wonder', 'teachers', 'silently', 'judging', 'ampxb', 'filler', 'filter', 'flicker', 'snicker', 'bicker', 'clicker', 'uncle', 'got', 'married', 'uncle', 'got', 'married', 'beautiful', 'wife', 'would', 'like', 'present', 'something', 'couldnt', 'think', 'anything', 'else', 'tell', 'guys', 'congratulations', 'uncle', 'jeremy', 'im', 'happy', 'sad', 'story', 'girls', 'break', 'dont', 'need', 'karma', 'go', 'suport', 'much', 'redit', 'karma', 'considered', 'lot', 'two', 'days', 'ago', 'marked', 'year', 'anniversary', 'redit', 'time', 'accumulated', 'bit', 'karma', 'wondering', 'much', 'karma', 'considered', 'lot', 'cat', 'attack', 'cat', 'decided', 'jump', 'underneath', 'chair', 'attack', 'barely', 'even', 'scratched', 'cat', 'annoying', 'name', 'edyedmond', 'hes', 'always', 'surprising', 'us', 'time', 'hes', 'super', 'friendly', 'fun', 'times', 'first', 'youtube', 'video', 'made', 'closer', 'today', 'look', 'months', 'years', 'months', 'since', 'video', 'made', 'back', 'video', 'made', 'years', 'months', 'away', 'december', 'chinese', 'people', 'speak', 'chinese', 'difficult', 'learn', 'easier', 'language', 'like', 'english', 'spanish', 'speak', 'like', 'languages', 'china', 'wont', 'list', 'edit', 'actually', 'speak', 'lot', 'ok', 'draw', 'portrait', 'im', 'bored', 'need', 'inspiration', 'yeah', 'idk', 'ig', 'ill', 'pick', 'favorite', 'draw', 'recommend', 'music', 'listen', 'im', 'bored', 'cant', 'fall', 'asleep', 'guys', 'know', 'good', 'songs', 'bands', 'tried', 'saying', 'get', 'mil', 'subs', 'reason', 'got', 'lot', 'hate', 'boy', 'joke', 'guys', 'allowed', 'switch', 'cameras', 'online', 'class', 'im', 'maybe', 'american', 'thing', 'idk', 'anyone', 'worried', 'college', 'remember', 'one', 'thing', 'kaitlyn', 'bennett', 'get', 'college', 'finally', 'year', 'learners', 'permit', 'finally', 'took', 'drivers', 'license', 'test', 'today', 'passed', 'redit', 'costs', 'billion', 'raise', 'money', 'buy', 'redit', 'make', 'things', 'crash', 'quicker', 'please', 'spread', 'news', 'god', 'princess', 'frog', 'underrated', 'disney', 'princess', 'movie', 'probably', 'favorite', 'disney', 'princess', 'movies', 'want', 'feel', 'wanted', 'someone', 'rob', 'bank', 'whole', 'police', 'looking', 'works', 'everytime', 'depressed', 'stop', 'depressed', 'hapy', 'draw', 'part', 'people', 'hate', 'british', 'uniforms', 'look', 'pretty', 'dont', 'understand', 'people', 'think', 'theyre', 'ugly', 'join', 'minecraft', 'serves', 'ps', 'recently', 'bought', 'minecraft', 'dont', 'know', 'also', 'ps', 'plus', 'necessary', 'got', 'writing', 'essay', 'book', 'didnt', 'read', 'clas', 'write', 'minutes', 'yo', 'lets', 'chat', 'hmu', 'interested', 'tryna', 'make', 'friends', 'also', 'im', 'bored', 'thought', 'dieing', 'make', 'hapyi', 'plan', 'going', 'happen', 'wasnt', 'waiting', 'something', 'would', 'go', 'right', 'thoughts', 'excite', 'im', 'still', 'alive', 'im', 'deleting', 'redit', 'tomorowthanks', 'kind', 'messages', 'place', 'fucking', 'toxic', 'continue', 'u', 'wan', 'na', 'talk', 'discord', 'aquamarine', 'writing', 'something', 'positive', 'day', 'day', 'slept', 'night', 'wasnt', 'tired', 'today', 'fun', 'fact', 'never', 'using', 'skeleton', 'even', 'yet', 'dark', 'outside', 'why', 'getting', 'ridiculous', 'sun', 'needs', 'stop', 'slacking', 'listening', 'songs', 'sdcardmusichans', 'zimerinceptionmombasawav', 'surround', 'sound', 'soundalive', 'thoughts', 'cringyembarasing', 'alternate', 'scenarios', 'almost', 'hapened', 'life', 'name', 'mood', 'ill', 'recommend', 'song', 'try', 'pick', 'song', 'enjoy', 'based', 'mood', 'enjoy', 'whats', 'song', 'recommend', 'everyone', 'matter', 'genre', 'like', 'song', 'recommend', 'everyone', 'change', 'ios', 'ap', 'logos', 'photos', 'im', 'honestly', 'know', 'change', 'ap', 'logos', 'help', 'spicy', 'fried', 'chicken', 'gtgtgtgtgt', 'spice', 'tender', 'meat', 'aroma', 'everything', 'good', 'stalker', 'metro', 'fallout', 'want', 'hear', 'opiniuns', 'games', 'funniest', 'comment', 'gets', 'free', 'helpful', 'award', 'really', 'need', 'laugh', 'e', 'lalalalalalalalalalalalalalalalalalalalalalala', 'brbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrb', 'dont', 'like', 'emojis', 'make', 'exceptions', 'ones', 'williams', 'got', 'investment', 'dont', 'know', 'investments', 'go', 'williams', 'go', 'ucolstarfish', 'favorite', 'reditor', 'ucolstarfish', 'favorite', 'reditor', 'ill', 'best', 'user', 'teenagers', 'competitors', 'turned', 'stone', 'methodsjust', 'purely', 'theoretic', 'discussion', 'easiest', 'ways', 'would', 'prefered', 'way', 'least', 'impact', 'family', 'least', 'destruction', 'body', 'sleeping', 'pilshow', 'kill', 'effectively', 'using', 'sleeping', 'pills', 'alcohol', 'like', 'vodka', 'dont', 'want', 'end', 'vegetable', 'holds', 'back', 'thats', 'im', 'asking', 'friends', 'someone', 'please', 'please', 'tell', 'toim', 'good', 'person', 'want', 'stop', 'want', 'it', 'stop', 'b', 'ad', 'im', 'scared', 'would', 'happen', 'want', 'dont', 'know', 'hurt', 'friends', 'hey', 'stalked', 'fault', 'first', 'plae', 'c', 'saw', 'lies', 'lies', 'lies', 'lies', 'lies', 'dont', 'think', 'gd', 'wants', 'anymore', 'think', 'im', 'supposed', 'gone', 'mg', 'xanax', 'thinking', 'taking', 'dont', 'know', 'im', 'even', 'postingits', 'much', 'hurts', 'everyday', 'sleep', 'peace', 'want', 'forever', 'day', 'one', 'posting', 'something', 'interesting', 'happens', 'qwertyiopasdfghjklzxcvbnm', 'guess', 'cant', 'sleep', 'supposed', 'die', 'sleep', 'cant', 'sleep', 'dont', 'think', 'ill', 'itits', 'awfully', 'temping', 'though', 'going', 'rough', 'patch', 'see', 'reason', 'one', 'actually', 'loves', 'everyone', 'faking', 'caring', 'meno', 'one', 'actually', 'cares', 'listen', 'understand', 'im', 'fault', 'everything', 'nothing', 'reversable', 'nothing', 'makes', 'happy', 'absolutely', 'nothing', 'plan', 'go', 'outside', 'city', 'hang', 'tree', 'even', 'picked', 'specific', 'tree', 'easy', 'climb', 'place', 'tie', 'rope', 'thick', 'enough', 'hold', 'weight', 'reasons', 'left', 'heres', 'year', 'half', 'long', 'relationship', 'ended', 'peoplethink', 'im', 'takinglying', 'suicidal', 'family', 'splitting', 'sexual', 'assault', 'school', 'sucks', 'anyone', 'talk', 'im', 'close', 'want', 'either', 'go', 'away', 'ill', 'make', 'go', 'away', 'im', 'therapy', 'meds', 'kinda', 'gone', 'last', 'resorts', 'times', 'police', 'hospital', 'finally', 'told', 'crush', 'liked', 'likes', 'back', 'im', 'super', 'happy', 'dd'] 670

### i. Remove capitalization/ Case normalization

In [23]:
normal_tokens = []
for token in clean_repeat_tokens:
    normal_tokens.append(token.lower())

print(normal_tokens, len(normal_tokens))

['teachers', 'seeing', 'submit', 'assignment', 'wonder', 'teachers', 'silently', 'judging', 'ampxb', 'filler', 'filter', 'flicker', 'snicker', 'bicker', 'clicker', 'uncle', 'got', 'married', 'uncle', 'got', 'married', 'beautiful', 'wife', 'would', 'like', 'present', 'something', 'couldnt', 'think', 'anything', 'else', 'tell', 'guys', 'congratulations', 'uncle', 'jeremy', 'im', 'happy', 'sad', 'story', 'girls', 'break', 'dont', 'need', 'karma', 'go', 'suport', 'much', 'redit', 'karma', 'considered', 'lot', 'two', 'days', 'ago', 'marked', 'year', 'anniversary', 'redit', 'time', 'accumulated', 'bit', 'karma', 'wondering', 'much', 'karma', 'considered', 'lot', 'cat', 'attack', 'cat', 'decided', 'jump', 'underneath', 'chair', 'attack', 'barely', 'even', 'scratched', 'cat', 'annoying', 'name', 'edyedmond', 'hes', 'always', 'surprising', 'us', 'time', 'hes', 'super', 'friendly', 'fun', 'times', 'first', 'youtube', 'video', 'made', 'closer', 'today', 'look', 'months', 'years', 'months', 'since', 'video', 'made', 'back', 'video', 'made', 'years', 'months', 'away', 'december', 'chinese', 'people', 'speak', 'chinese', 'difficult', 'learn', 'easier', 'language', 'like', 'english', 'spanish', 'speak', 'like', 'languages', 'china', 'wont', 'list', 'edit', 'actually', 'speak', 'lot', 'ok', 'draw', 'portrait', 'im', 'bored', 'need', 'inspiration', 'yeah', 'idk', 'ig', 'ill', 'pick', 'favorite', 'draw', 'recommend', 'music', 'listen', 'im', 'bored', 'cant', 'fall', 'asleep', 'guys', 'know', 'good', 'songs', 'bands', 'tried', 'saying', 'get', 'mil', 'subs', 'reason', 'got', 'lot', 'hate', 'boy', 'joke', 'guys', 'allowed', 'switch', 'cameras', 'online', 'class', 'im', 'maybe', 'american', 'thing', 'idk', 'anyone', 'worried', 'college', 'remember', 'one', 'thing', 'kaitlyn', 'bennett', 'get', 'college', 'finally', 'year', 'learners', 'permit', 'finally', 'took', 'drivers', 'license', 'test', 'today', 'passed', 'redit', 'costs', 'billion', 'raise', 'money', 'buy', 'redit', 'make', 'things', 'crash', 'quicker', 'please', 'spread', 'news', 'god', 'princess', 'frog', 'underrated', 'disney', 'princess', 'movie', 'probably', 'favorite', 'disney', 'princess', 'movies', 'want', 'feel', 'wanted', 'someone', 'rob', 'bank', 'whole', 'police', 'looking', 'works', 'everytime', 'depressed', 'stop', 'depressed', 'hapy', 'draw', 'part', 'people', 'hate', 'british', 'uniforms', 'look', 'pretty', 'dont', 'understand', 'people', 'think', 'theyre', 'ugly', 'join', 'minecraft', 'serves', 'ps', 'recently', 'bought', 'minecraft', 'dont', 'know', 'also', 'ps', 'plus', 'necessary', 'got', 'writing', 'essay', 'book', 'didnt', 'read', 'clas', 'write', 'minutes', 'yo', 'lets', 'chat', 'hmu', 'interested', 'tryna', 'make', 'friends', 'also', 'im', 'bored', 'thought', 'dieing', 'make', 'hapyi', 'plan', 'going', 'happen', 'wasnt', 'waiting', 'something', 'would', 'go', 'right', 'thoughts', 'excite', 'im', 'still', 'alive', 'im', 'deleting', 'redit', 'tomorowthanks', 'kind', 'messages', 'place', 'fucking', 'toxic', 'continue', 'u', 'wan', 'na', 'talk', 'discord', 'aquamarine', 'writing', 'something', 'positive', 'day', 'day', 'slept', 'night', 'wasnt', 'tired', 'today', 'fun', 'fact', 'never', 'using', 'skeleton', 'even', 'yet', 'dark', 'outside', 'why', 'getting', 'ridiculous', 'sun', 'needs', 'stop', 'slacking', 'listening', 'songs', 'sdcardmusichans', 'zimerinceptionmombasawav', 'surround', 'sound', 'soundalive', 'thoughts', 'cringyembarasing', 'alternate', 'scenarios', 'almost', 'hapened', 'life', 'name', 'mood', 'ill', 'recommend', 'song', 'try', 'pick', 'song', 'enjoy', 'based', 'mood', 'enjoy', 'whats', 'song', 'recommend', 'everyone', 'matter', 'genre', 'like', 'song', 'recommend', 'everyone', 'change', 'ios', 'ap', 'logos', 'photos', 'im', 'honestly', 'know', 'change', 'ap', 'logos', 'help', 'spicy', 'fried', 'chicken', 'gtgtgtgtgt', 'spice', 'tender', 'meat', 'aroma', 'everything', 'good', 'stalker', 'metro', 'fallout', 'want', 'hear', 'opiniuns', 'games', 'funniest', 'comment', 'gets', 'free', 'helpful', 'award', 'really', 'need', 'laugh', 'e', 'lalalalalalalalalalalalalalalalalalalalalalala', 'brbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrb', 'dont', 'like', 'emojis', 'make', 'exceptions', 'ones', 'williams', 'got', 'investment', 'dont', 'know', 'investments', 'go', 'williams', 'go', 'ucolstarfish', 'favorite', 'reditor', 'ucolstarfish', 'favorite', 'reditor', 'ill', 'best', 'user', 'teenagers', 'competitors', 'turned', 'stone', 'methodsjust', 'purely', 'theoretic', 'discussion', 'easiest', 'ways', 'would', 'prefered', 'way', 'least', 'impact', 'family', 'least', 'destruction', 'body', 'sleeping', 'pilshow', 'kill', 'effectively', 'using', 'sleeping', 'pills', 'alcohol', 'like', 'vodka', 'dont', 'want', 'end', 'vegetable', 'holds', 'back', 'thats', 'im', 'asking', 'friends', 'someone', 'please', 'please', 'tell', 'toim', 'good', 'person', 'want', 'stop', 'want', 'it', 'stop', 'b', 'ad', 'im', 'scared', 'would', 'happen', 'want', 'dont', 'know', 'hurt', 'friends', 'hey', 'stalked', 'fault', 'first', 'plae', 'c', 'saw', 'lies', 'lies', 'lies', 'lies', 'lies', 'dont', 'think', 'gd', 'wants', 'anymore', 'think', 'im', 'supposed', 'gone', 'mg', 'xanax', 'thinking', 'taking', 'dont', 'know', 'im', 'even', 'postingits', 'much', 'hurts', 'everyday', 'sleep', 'peace', 'want', 'forever', 'day', 'one', 'posting', 'something', 'interesting', 'happens', 'qwertyiopasdfghjklzxcvbnm', 'guess', 'cant', 'sleep', 'supposed', 'die', 'sleep', 'cant', 'sleep', 'dont', 'think', 'ill', 'itits', 'awfully', 'temping', 'though', 'going', 'rough', 'patch', 'see', 'reason', 'one', 'actually', 'loves', 'everyone', 'faking', 'caring', 'meno', 'one', 'actually', 'cares', 'listen', 'understand', 'im', 'fault', 'everything', 'nothing', 'reversable', 'nothing', 'makes', 'happy', 'absolutely', 'nothing', 'plan', 'go', 'outside', 'city', 'hang', 'tree', 'even', 'picked', 'specific', 'tree', 'easy', 'climb', 'place', 'tie', 'rope', 'thick', 'enough', 'hold', 'weight', 'reasons', 'left', 'heres', 'year', 'half', 'long', 'relationship', 'ended', 'peoplethink', 'im', 'takinglying', 'suicidal', 'family', 'splitting', 'sexual', 'assault', 'school', 'sucks', 'anyone', 'talk', 'im', 'close', 'want', 'either', 'go', 'away', 'ill', 'make', 'go', 'away', 'im', 'therapy', 'meds', 'kinda', 'gone', 'last', 'resorts', 'times', 'police', 'hospital', 'finally', 'told', 'crush', 'liked', 'likes', 'back', 'im', 'super', 'happy', 'dd'] 670

### j. Remove Whitespaces, for instance, He llo → Hello

In [24]:
# remove white spaces and tabs
# clean_data = clean_data.replace("\\t", " ")
# clean_data = re.sub(re.compile(r'\s+'), " ", clean_data)

### k. Typo Correction/ Misspelled words: big “dada” → big “data”;

### Spell Correction
Spelling errors happen a lot for various reasons such as proximity between keyboards and other reasons.In this section, we want to learn how to detect and correct it.

- Spell Error Detection
    - We make a dictionary of language words, where we can use the **wordnet corpus**. **The words that are not in this data set as dictionary words are considered misspelled**.

- Spell Error Correction Method
    1. We extract the list of **synonyms** or **SynSets** of the word, for which we can also use NLTK and Wordnet.
    2. We choose the word that has the s**mallest Editing distance** as the corrected word.

#### What is Editing distance?
The distance of converting one word to another using deletion, insertion and substitution of characters. Each of these operations has a point.
- [Delete: 1 point] [Insert: 1 point] [Substitution: 2 point]
- Example: We want to calculate the editing distance between two words, **there** are **three**
    - one delete + one insert : (there->thre) and (thre->three) => ED = 1+1=2

#### spelling correction implementation
To spelling correction in this project, we used the **autocorrect** library.
- we also implemented this operation from scratch with the of **NLTK** and **Wordnet** based on the editing distance and the given description, which is available at the following address. [Custom_Spell_Corrector](docs/Custom_Spell_Corrector.ipynb)

In [25]:
from autocorrect import Speller

speller = Speller()

print(speller("big dada"))
print(speller("corect"))

big data
correct

In [ ]:


speller = Speller()

clean_spell_tokens = []
for token in normal_tokens:
    clean = speller(token)
    if clean != token: print(token, "=> clean spell: ", clean)
    clean_spell_tokens.append(clean)

print(clean_spell_tokens, len(clean_spell_tokens))

ampxb => clean spell:  amp
snicker => clean spell:  sticker
bicker => clean spell:  kicker
clicker => clean spell:  clicked
suport => clean spell:  sport
redit => clean spell:  edit
redit => clean spell:  edit
idk => clean spell:  id
idk => clean spell:  id
redit => clean spell:  edit
redit => clean spell:  edit
everytime => clean spell:  overtime
hapy => clean spell:  happy
clas => clean spell:  class
hmu => clean spell:  hu
tryna => clean spell:  try
dieing => clean spell:  diving
hapyi => clean spell:  happy
redit => clean spell:  edit
slacking => clean spell:  lacking
hapened => clean spell:  happened
opiniuns => clean spell:  opinions
emojis => clean spell:  emoji
reditor => clean spell:  editor
reditor => clean spell:  editor
prefered => clean spell:  preferred
pilshow => clean spell:  pillow
toim => clean spell:  tom
plae => clean spell:  place
xanax => clean spell:  canal
postingits => clean spell:  postings
itits => clean spell:  itis
temping => clean spell:  tempting
meno => clean spell:  men
reversable => clean spell:  reversible
meds => clean spell:  mens
['teachers', 'seeing', 'submit', 'assignment', 'wonder', 'teachers', 'silently', 'judging', 'amp', 'filler', 'filter', 'flicker', 'sticker', 'kicker', 'clicked', 'uncle', 'got', 'married', 'uncle', 'got', 'married', 'beautiful', 'wife', 'would', 'like', 'present', 'something', 'couldnt', 'think', 'anything', 'else', 'tell', 'guys', 'congratulations', 'uncle', 'jeremy', 'im', 'happy', 'sad', 'story', 'girls', 'break', 'dont', 'need', 'karma', 'go', 'sport', 'much', 'edit', 'karma', 'considered', 'lot', 'two', 'days', 'ago', 'marked', 'year', 'anniversary', 'edit', 'time', 'accumulated', 'bit', 'karma', 'wondering', 'much', 'karma', 'considered', 'lot', 'cat', 'attack', 'cat', 'decided', 'jump', 'underneath', 'chair', 'attack', 'barely', 'even', 'scratched', 'cat', 'annoying', 'name', 'edyedmond', 'hes', 'always', 'surprising', 'us', 'time', 'hes', 'super', 'friendly', 'fun', 'times', 'first', 'youtube', 'video', 'made', 'closer', 'today', 'look', 'months', 'years', 'months', 'since', 'video', 'made', 'back', 'video', 'made', 'years', 'months', 'away', 'december', 'chinese', 'people', 'speak', 'chinese', 'difficult', 'learn', 'easier', 'language', 'like', 'english', 'spanish', 'speak', 'like', 'languages', 'china', 'wont', 'list', 'edit', 'actually', 'speak', 'lot', 'ok', 'draw', 'portrait', 'im', 'bored', 'need', 'inspiration', 'yeah', 'id', 'ig', 'ill', 'pick', 'favorite', 'draw', 'recommend', 'music', 'listen', 'im', 'bored', 'cant', 'fall', 'asleep', 'guys', 'know', 'good', 'songs', 'bands', 'tried', 'saying', 'get', 'mil', 'subs', 'reason', 'got', 'lot', 'hate', 'boy', 'joke', 'guys', 'allowed', 'switch', 'cameras', 'online', 'class', 'im', 'maybe', 'american', 'thing', 'id', 'anyone', 'worried', 'college', 'remember', 'one', 'thing', 'kaitlyn', 'bennett', 'get', 'college', 'finally', 'year', 'learners', 'permit', 'finally', 'took', 'drivers', 'license', 'test', 'today', 'passed', 'edit', 'costs', 'billion', 'raise', 'money', 'buy', 'edit', 'make', 'things', 'crash', 'quicker', 'please', 'spread', 'news', 'god', 'princess', 'frog', 'underrated', 'disney', 'princess', 'movie', 'probably', 'favorite', 'disney', 'princess', 'movies', 'want', 'feel', 'wanted', 'someone', 'rob', 'bank', 'whole', 'police', 'looking', 'works', 'overtime', 'depressed', 'stop', 'depressed', 'happy', 'draw', 'part', 'people', 'hate', 'british', 'uniforms', 'look', 'pretty', 'dont', 'understand', 'people', 'think', 'theyre', 'ugly', 'join', 'minecraft', 'serves', 'ps', 'recently', 'bought', 'minecraft', 'dont', 'know', 'also', 'ps', 'plus', 'necessary', 'got', 'writing', 'essay', 'book', 'didnt', 'read', 'class', 'write', 'minutes', 'yo', 'lets', 'chat', 'hu', 'interested', 'try', 'make', 'friends', 'also', 'im', 'bored', 'thought', 'diving', 'make', 'happy', 'plan', 'going', 'happen', 'wasnt', 'waiting', 'something', 'would', 'go', 'right', 'thoughts', 'excite', 'im', 'still', 'alive', 'im', 'deleting', 'edit', 'tomorowthanks', 'kind', 'messages', 'place', 'fucking', 'toxic', 'continue', 'u', 'wan', 'na', 'talk', 'discord', 'aquamarine', 'writing', 'something', 'positive', 'day', 'day', 'slept', 'night', 'wasnt', 'tired', 'today', 'fun', 'fact', 'never', 'using', 'skeleton', 'even', 'yet', 'dark', 'outside', 'why', 'getting', 'ridiculous', 'sun', 'needs', 'stop', 'lacking', 'listening', 'songs', 'sdcardmusichans', 'zimerinceptionmombasawav', 'surround', 'sound', 'soundalive', 'thoughts', 'cringyembarasing', 'alternate', 'scenarios', 'almost', 'happened', 'life', 'name', 'mood', 'ill', 'recommend', 'song', 'try', 'pick', 'song', 'enjoy', 'based', 'mood', 'enjoy', 'whats', 'song', 'recommend', 'everyone', 'matter', 'genre', 'like', 'song', 'recommend', 'everyone', 'change', 'ios', 'ap', 'logos', 'photos', 'im', 'honestly', 'know', 'change', 'ap', 'logos', 'help', 'spicy', 'fried', 'chicken', 'gtgtgtgtgt', 'spice', 'tender', 'meat', 'aroma', 'everything', 'good', 'stalker', 'metro', 'fallout', 'want', 'hear', 'opinions', 'games', 'funniest', 'comment', 'gets', 'free', 'helpful', 'award', 'really', 'need', 'laugh', 'e', 'lalalalalalalalalalalalalalalalalalalalalalala', 'brbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrb', 'dont', 'like', 'emoji', 'make', 'exceptions', 'ones', 'williams', 'got', 'investment', 'dont', 'know', 'investments', 'go', 'williams', 'go', 'ucolstarfish', 'favorite', 'editor', 'ucolstarfish', 'favorite', 'editor', 'ill', 'best', 'user', 'teenagers', 'competitors', 'turned', 'stone', 'methodsjust', 'purely', 'theoretic', 'discussion', 'easiest', 'ways', 'would', 'preferred', 'way', 'least', 'impact', 'family', 'least', 'destruction', 'body', 'sleeping', 'pillow', 'kill', 'effectively', 'using', 'sleeping', 'pills', 'alcohol', 'like', 'vodka', 'dont', 'want', 'end', 'vegetable', 'holds', 'back', 'thats', 'im', 'asking', 'friends', 'someone', 'please', 'please', 'tell', 'tom', 'good', 'person', 'want', 'stop', 'want', 'it', 'stop', 'b', 'ad', 'im', 'scared', 'would', 'happen', 'want', 'dont', 'know', 'hurt', 'friends', 'hey', 'stalked', 'fault', 'first', 'place', 'c', 'saw', 'lies', 'lies', 'lies', 'lies', 'lies', 'dont', 'think', 'gd', 'wants', 'anymore', 'think', 'im', 'supposed', 'gone', 'mg', 'canal', 'thinking', 'taking', 'dont', 'know', 'im', 'even', 'postings', 'much', 'hurts', 'everyday', 'sleep', 'peace', 'want', 'forever', 'day', 'one', 'posting', 'something', 'interesting', 'happens', 'qwertyiopasdfghjklzxcvbnm', 'guess', 'cant', 'sleep', 'supposed', 'die', 'sleep', 'cant', 'sleep', 'dont', 'think', 'ill', 'itis', 'awfully', 'tempting', 'though', 'going', 'rough', 'patch', 'see', 'reason', 'one', 'actually', 'loves', 'everyone', 'faking', 'caring', 'men', 'one', 'actually', 'cares', 'listen', 'understand', 'im', 'fault', 'everything', 'nothing', 'reversible', 'nothing', 'makes', 'happy', 'absolutely', 'nothing', 'plan', 'go', 'outside', 'city', 'hang', 'tree', 'even', 'picked', 'specific', 'tree', 'easy', 'climb', 'place', 'tie', 'rope', 'thick', 'enough', 'hold', 'weight', 'reasons', 'left', 'heres', 'year', 'half', 'long', 'relationship', 'ended', 'peoplethink', 'im', 'takinglying', 'suicidal', 'family', 'splitting', 'sexual', 'assault', 'school', 'sucks', 'anyone', 'talk', 'im', 'close', 'want', 'either', 'go', 'away', 'ill', 'make', 'go', 'away', 'im', 'therapy', 'mens', 'kinda', 'gone', 'last', 'resorts', 'times', 'police', 'hospital', 'finally', 'told', 'crush', 'liked', 'likes', 'back', 'im', 'super', 'happy', 'dd'] 670

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
      Stemming or lemmatization
</center></p></h1>

In [ ]:

stemmer = PorterStemmer()
stemmer.stem("information")

'inform'

In [ ]:

stemmer = PorterStemmer()

stem_tokens = []
for token in clean_spell_tokens:
    clean = stemmer.stem(token)
    if clean != token: print(token, "=>", clean)
    stem_tokens.append(clean)

print(stem_tokens, len(stem_tokens))

teachers => teacher
seeing => see
assignment => assign
teachers => teacher
silently => silent
judging => judg
clicked => click
uncle => uncl
married => marri
uncle => uncl
married => marri
beautiful => beauti
something => someth
anything => anyth
else => els
guys => guy
congratulations => congratul
uncle => uncl
jeremy => jeremi
happy => happi
story => stori
girls => girl
considered => consid
days => day
marked => mark
anniversary => anniversari
accumulated => accumul
wondering => wonder
considered => consid
decided => decid
barely => bare
scratched => scratch
annoying => annoy
hes => he
always => alway
surprising => surpris
hes => he
friendly => friendli
times => time
youtube => youtub
months => month
years => year
months => month
since => sinc
years => year
months => month
december => decemb
chinese => chines
people => peopl
chinese => chines
language => languag
languages => languag
actually => actual
bored => bore
inspiration => inspir
favorite => favorit
bored => bore
guys => guy
songs => song
bands => band
tried => tri
saying => say
subs => sub
guys => guy
allowed => allow
cameras => camera
online => onlin
maybe => mayb
anyone => anyon
worried => worri
college => colleg
remember => rememb
college => colleg
finally => final
learners => learner
finally => final
drivers => driver
license => licens
passed => pass
costs => cost
raise => rais
things => thing
please => pleas
underrated => underr
movie => movi
probably => probabl
favorite => favorit
movies => movi
wanted => want
someone => someon
police => polic
looking => look
works => work
overtime => overtim
depressed => depress
depressed => depress
happy => happi
people => peopl
uniforms => uniform
pretty => pretti
people => peopl
theyre => theyr
ugly => ugli
serves => serv
recently => recent
plus => plu
necessary => necessari
writing => write
minutes => minut
lets => let
interested => interest
try => tri
friends => friend
bored => bore
diving => dive
happy => happi
going => go
waiting => wait
something => someth
thoughts => thought
excite => excit
alive => aliv
deleting => delet
tomorowthanks => tomorowthank
messages => messag
fucking => fuck
continue => continu
aquamarine => aquamarin
writing => write
something => someth
positive => posit
tired => tire
using => use
outside => outsid
why => whi
getting => get
ridiculous => ridicul
needs => need
lacking => lack
listening => listen
songs => song
sdcardmusichans => sdcardmusichan
soundalive => soundal
thoughts => thought
cringyembarasing => cringyembaras
alternate => altern
scenarios => scenario
happened => happen
try => tri
based => base
whats => what
everyone => everyon
genre => genr
everyone => everyon
change => chang
ios => io
logos => logo
photos => photo
honestly => honestli
change => chang
logos => logo
spicy => spici
fried => fri
everything => everyth
opinions => opinion
games => game
gets => get
helpful => help
really => realli
exceptions => except
ones => one
williams => william
investment => invest
investments => invest
williams => william
favorite => favorit
favorite => favorit
teenagers => teenag
competitors => competitor
turned => turn
purely => pure
theoretic => theoret
discussion => discuss
ways => way
preferred => prefer
family => famili
destruction => destruct
body => bodi
sleeping => sleep
effectively => effect
using => use
sleeping => sleep
pills => pill
vegetable => veget
holds => hold
thats => that
asking => ask
friends => friend
someone => someon
please => pleas
please => pleas
scared => scare
friends => friend
stalked => stalk
lies => lie
lies => lie
lies => lie
lies => lie
lies => lie
wants => want
anymore => anymor
supposed => suppos
thinking => think
taking => take
postings => post
hurts => hurt
peace => peac
forever => forev
posting => post
something => someth
interesting => interest
happens => happen
supposed => suppos
itis => iti
awfully => aw
tempting => tempt
going => go
actually => actual
loves => love
everyone => everyon
faking => fake
caring => care
actually => actual
cares => care
everything => everyth
nothing => noth
reversible => revers
nothing => noth
makes => make
happy => happi
absolutely => absolut
nothing => noth
outside => outsid
city => citi
picked => pick
specific => specif
easy => easi
reasons => reason
heres => here
ended => end
takinglying => takingli
suicidal => suicid
family => famili
splitting => split
sucks => suck
anyone => anyon
therapy => therapi
mens => men
resorts => resort
times => time
police => polic
hospital => hospit
finally => final
liked => like
likes => like
happy => happi
['teacher', 'see', 'submit', 'assign', 'wonder', 'teacher', 'silent', 'judg', 'amp', 'filler', 'filter', 'flicker', 'sticker', 'kicker', 'click', 'uncl', 'got', 'marri', 'uncl', 'got', 'marri', 'beauti', 'wife', 'would', 'like', 'present', 'someth', 'couldnt', 'think', 'anyth', 'els', 'tell', 'guy', 'congratul', 'uncl', 'jeremi', 'im', 'happi', 'sad', 'stori', 'girl', 'break', 'dont', 'need', 'karma', 'go', 'sport', 'much', 'edit', 'karma', 'consid', 'lot', 'two', 'day', 'ago', 'mark', 'year', 'anniversari', 'edit', 'time', 'accumul', 'bit', 'karma', 'wonder', 'much', 'karma', 'consid', 'lot', 'cat', 'attack', 'cat', 'decid', 'jump', 'underneath', 'chair', 'attack', 'bare', 'even', 'scratch', 'cat', 'annoy', 'name', 'edyedmond', 'he', 'alway', 'surpris', 'us', 'time', 'he', 'super', 'friendli', 'fun', 'time', 'first', 'youtub', 'video', 'made', 'closer', 'today', 'look', 'month', 'year', 'month', 'sinc', 'video', 'made', 'back', 'video', 'made', 'year', 'month', 'away', 'decemb', 'chines', 'peopl', 'speak', 'chines', 'difficult', 'learn', 'easier', 'languag', 'like', 'english', 'spanish', 'speak', 'like', 'languag', 'china', 'wont', 'list', 'edit', 'actual', 'speak', 'lot', 'ok', 'draw', 'portrait', 'im', 'bore', 'need', 'inspir', 'yeah', 'id', 'ig', 'ill', 'pick', 'favorit', 'draw', 'recommend', 'music', 'listen', 'im', 'bore', 'cant', 'fall', 'asleep', 'guy', 'know', 'good', 'song', 'band', 'tri', 'say', 'get', 'mil', 'sub', 'reason', 'got', 'lot', 'hate', 'boy', 'joke', 'guy', 'allow', 'switch', 'camera', 'onlin', 'class', 'im', 'mayb', 'american', 'thing', 'id', 'anyon', 'worri', 'colleg', 'rememb', 'one', 'thing', 'kaitlyn', 'bennett', 'get', 'colleg', 'final', 'year', 'learner', 'permit', 'final', 'took', 'driver', 'licens', 'test', 'today', 'pass', 'edit', 'cost', 'billion', 'rais', 'money', 'buy', 'edit', 'make', 'thing', 'crash', 'quicker', 'pleas', 'spread', 'news', 'god', 'princess', 'frog', 'underr', 'disney', 'princess', 'movi', 'probabl', 'favorit', 'disney', 'princess', 'movi', 'want', 'feel', 'want', 'someon', 'rob', 'bank', 'whole', 'polic', 'look', 'work', 'overtim', 'depress', 'stop', 'depress', 'happi', 'draw', 'part', 'peopl', 'hate', 'british', 'uniform', 'look', 'pretti', 'dont', 'understand', 'peopl', 'think', 'theyr', 'ugli', 'join', 'minecraft', 'serv', 'ps', 'recent', 'bought', 'minecraft', 'dont', 'know', 'also', 'ps', 'plu', 'necessari', 'got', 'write', 'essay', 'book', 'didnt', 'read', 'class', 'write', 'minut', 'yo', 'let', 'chat', 'hu', 'interest', 'tri', 'make', 'friend', 'also', 'im', 'bore', 'thought', 'dive', 'make', 'happi', 'plan', 'go', 'happen', 'wasnt', 'wait', 'someth', 'would', 'go', 'right', 'thought', 'excit', 'im', 'still', 'aliv', 'im', 'delet', 'edit', 'tomorowthank', 'kind', 'messag', 'place', 'fuck', 'toxic', 'continu', 'u', 'wan', 'na', 'talk', 'discord', 'aquamarin', 'write', 'someth', 'posit', 'day', 'day', 'slept', 'night', 'wasnt', 'tire', 'today', 'fun', 'fact', 'never', 'use', 'skeleton', 'even', 'yet', 'dark', 'outsid', 'whi', 'get', 'ridicul', 'sun', 'need', 'stop', 'lack', 'listen', 'song', 'sdcardmusichan', 'zimerinceptionmombasawav', 'surround', 'sound', 'soundal', 'thought', 'cringyembaras', 'altern', 'scenario', 'almost', 'happen', 'life', 'name', 'mood', 'ill', 'recommend', 'song', 'tri', 'pick', 'song', 'enjoy', 'base', 'mood', 'enjoy', 'what', 'song', 'recommend', 'everyon', 'matter', 'genr', 'like', 'song', 'recommend', 'everyon', 'chang', 'io', 'ap', 'logo', 'photo', 'im', 'honestli', 'know', 'chang', 'ap', 'logo', 'help', 'spici', 'fri', 'chicken', 'gtgtgtgtgt', 'spice', 'tender', 'meat', 'aroma', 'everyth', 'good', 'stalker', 'metro', 'fallout', 'want', 'hear', 'opinion', 'game', 'funniest', 'comment', 'get', 'free', 'help', 'award', 'realli', 'need', 'laugh', 'e', 'lalalalalalalalalalalalalalalalalalalalalalala', 'brbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrb', 'dont', 'like', 'emoji', 'make', 'except', 'one', 'william', 'got', 'invest', 'dont', 'know', 'invest', 'go', 'william', 'go', 'ucolstarfish', 'favorit', 'editor', 'ucolstarfish', 'favorit', 'editor', 'ill', 'best', 'user', 'teenag', 'competitor', 'turn', 'stone', 'methodsjust', 'pure', 'theoret', 'discuss', 'easiest', 'way', 'would', 'prefer', 'way', 'least', 'impact', 'famili', 'least', 'destruct', 'bodi', 'sleep', 'pillow', 'kill', 'effect', 'use', 'sleep', 'pill', 'alcohol', 'like', 'vodka', 'dont', 'want', 'end', 'veget', 'hold', 'back', 'that', 'im', 'ask', 'friend', 'someon', 'pleas', 'pleas', 'tell', 'tom', 'good', 'person', 'want', 'stop', 'want', 'it', 'stop', 'b', 'ad', 'im', 'scare', 'would', 'happen', 'want', 'dont', 'know', 'hurt', 'friend', 'hey', 'stalk', 'fault', 'first', 'place', 'c', 'saw', 'lie', 'lie', 'lie', 'lie', 'lie', 'dont', 'think', 'gd', 'want', 'anymor', 'think', 'im', 'suppos', 'gone', 'mg', 'canal', 'think', 'take', 'dont', 'know', 'im', 'even', 'post', 'much', 'hurt', 'everyday', 'sleep', 'peac', 'want', 'forev', 'day', 'one', 'post', 'someth', 'interest', 'happen', 'qwertyiopasdfghjklzxcvbnm', 'guess', 'cant', 'sleep', 'suppos', 'die', 'sleep', 'cant', 'sleep', 'dont', 'think', 'ill', 'iti', 'aw', 'tempt', 'though', 'go', 'rough', 'patch', 'see', 'reason', 'one', 'actual', 'love', 'everyon', 'fake', 'care', 'men', 'one', 'actual', 'care', 'listen', 'understand', 'im', 'fault', 'everyth', 'noth', 'revers', 'noth', 'make', 'happi', 'absolut', 'noth', 'plan', 'go', 'outsid', 'citi', 'hang', 'tree', 'even', 'pick', 'specif', 'tree', 'easi', 'climb', 'place', 'tie', 'rope', 'thick', 'enough', 'hold', 'weight', 'reason', 'left', 'here', 'year', 'half', 'long', 'relationship', 'end', 'peoplethink', 'im', 'takingli', 'suicid', 'famili', 'split', 'sexual', 'assault', 'school', 'suck', 'anyon', 'talk', 'im', 'close', 'want', 'either', 'go', 'away', 'ill', 'make', 'go', 'away', 'im', 'therapi', 'men', 'kinda', 'gone', 'last', 'resort', 'time', 'polic', 'hospit', 'final', 'told', 'crush', 'like', 'like', 'back', 'im', 'super', 'happi', 'dd'] 670

In [ ]:


lemmatizer = WordNetLemmatizer() # by default Part of speach is Noun or Name
print(stemmer.stem("believes"))
print(lemmatizer.lemmatize("believes"))

believ
belief

In [ ]:


lemmatizer = WordNetLemmatizer() # by default Part of speach is Noun or Name

lem_tokens = []
for token in clean_spell_tokens:
    clean = lemmatizer.lemmatize(token)
    if clean != token: print(token, "=>", clean)
    lem_tokens.append(clean)

print(lem_tokens, len(lem_tokens))

teachers => teacher
teachers => teacher
guys => guy
congratulations => congratulation
girls => girl
days => day
hes => he
us => u
hes => he
times => time
months => month
years => year
months => month
years => year
months => month
languages => language
guys => guy
songs => song
bands => band
subs => sub
guys => guy
cameras => camera
learners => learner
drivers => driver
costs => cost
things => thing
movies => movie
works => work
uniforms => uniform
serves => serf
ps => p
ps => p
minutes => minute
lets => let
friends => friend
thoughts => thought
messages => message
needs => need
songs => song
thoughts => thought
scenarios => scenario
ios => io
logos => logo
photos => photo
logos => logo
opinions => opinion
games => game
gets => get
exceptions => exception
ones => one
investments => investment
teenagers => teenager
competitors => competitor
ways => way
pills => pill
holds => hold
friends => friend
friends => friend
lies => lie
lies => lie
lies => lie
lies => lie
lies => lie
wants => want
postings => posting
hurts => hurt
loves => love
cares => care
makes => make
reasons => reason
heres => here
sucks => suck
mens => men
resorts => resort
times => time
likes => like
['teacher', 'seeing', 'submit', 'assignment', 'wonder', 'teacher', 'silently', 'judging', 'amp', 'filler', 'filter', 'flicker', 'sticker', 'kicker', 'clicked', 'uncle', 'got', 'married', 'uncle', 'got', 'married', 'beautiful', 'wife', 'would', 'like', 'present', 'something', 'couldnt', 'think', 'anything', 'else', 'tell', 'guy', 'congratulation', 'uncle', 'jeremy', 'im', 'happy', 'sad', 'story', 'girl', 'break', 'dont', 'need', 'karma', 'go', 'sport', 'much', 'edit', 'karma', 'considered', 'lot', 'two', 'day', 'ago', 'marked', 'year', 'anniversary', 'edit', 'time', 'accumulated', 'bit', 'karma', 'wondering', 'much', 'karma', 'considered', 'lot', 'cat', 'attack', 'cat', 'decided', 'jump', 'underneath', 'chair', 'attack', 'barely', 'even', 'scratched', 'cat', 'annoying', 'name', 'edyedmond', 'he', 'always', 'surprising', 'u', 'time', 'he', 'super', 'friendly', 'fun', 'time', 'first', 'youtube', 'video', 'made', 'closer', 'today', 'look', 'month', 'year', 'month', 'since', 'video', 'made', 'back', 'video', 'made', 'year', 'month', 'away', 'december', 'chinese', 'people', 'speak', 'chinese', 'difficult', 'learn', 'easier', 'language', 'like', 'english', 'spanish', 'speak', 'like', 'language', 'china', 'wont', 'list', 'edit', 'actually', 'speak', 'lot', 'ok', 'draw', 'portrait', 'im', 'bored', 'need', 'inspiration', 'yeah', 'id', 'ig', 'ill', 'pick', 'favorite', 'draw', 'recommend', 'music', 'listen', 'im', 'bored', 'cant', 'fall', 'asleep', 'guy', 'know', 'good', 'song', 'band', 'tried', 'saying', 'get', 'mil', 'sub', 'reason', 'got', 'lot', 'hate', 'boy', 'joke', 'guy', 'allowed', 'switch', 'camera', 'online', 'class', 'im', 'maybe', 'american', 'thing', 'id', 'anyone', 'worried', 'college', 'remember', 'one', 'thing', 'kaitlyn', 'bennett', 'get', 'college', 'finally', 'year', 'learner', 'permit', 'finally', 'took', 'driver', 'license', 'test', 'today', 'passed', 'edit', 'cost', 'billion', 'raise', 'money', 'buy', 'edit', 'make', 'thing', 'crash', 'quicker', 'please', 'spread', 'news', 'god', 'princess', 'frog', 'underrated', 'disney', 'princess', 'movie', 'probably', 'favorite', 'disney', 'princess', 'movie', 'want', 'feel', 'wanted', 'someone', 'rob', 'bank', 'whole', 'police', 'looking', 'work', 'overtime', 'depressed', 'stop', 'depressed', 'happy', 'draw', 'part', 'people', 'hate', 'british', 'uniform', 'look', 'pretty', 'dont', 'understand', 'people', 'think', 'theyre', 'ugly', 'join', 'minecraft', 'serf', 'p', 'recently', 'bought', 'minecraft', 'dont', 'know', 'also', 'p', 'plus', 'necessary', 'got', 'writing', 'essay', 'book', 'didnt', 'read', 'class', 'write', 'minute', 'yo', 'let', 'chat', 'hu', 'interested', 'try', 'make', 'friend', 'also', 'im', 'bored', 'thought', 'diving', 'make', 'happy', 'plan', 'going', 'happen', 'wasnt', 'waiting', 'something', 'would', 'go', 'right', 'thought', 'excite', 'im', 'still', 'alive', 'im', 'deleting', 'edit', 'tomorowthanks', 'kind', 'message', 'place', 'fucking', 'toxic', 'continue', 'u', 'wan', 'na', 'talk', 'discord', 'aquamarine', 'writing', 'something', 'positive', 'day', 'day', 'slept', 'night', 'wasnt', 'tired', 'today', 'fun', 'fact', 'never', 'using', 'skeleton', 'even', 'yet', 'dark', 'outside', 'why', 'getting', 'ridiculous', 'sun', 'need', 'stop', 'lacking', 'listening', 'song', 'sdcardmusichans', 'zimerinceptionmombasawav', 'surround', 'sound', 'soundalive', 'thought', 'cringyembarasing', 'alternate', 'scenario', 'almost', 'happened', 'life', 'name', 'mood', 'ill', 'recommend', 'song', 'try', 'pick', 'song', 'enjoy', 'based', 'mood', 'enjoy', 'whats', 'song', 'recommend', 'everyone', 'matter', 'genre', 'like', 'song', 'recommend', 'everyone', 'change', 'io', 'ap', 'logo', 'photo', 'im', 'honestly', 'know', 'change', 'ap', 'logo', 'help', 'spicy', 'fried', 'chicken', 'gtgtgtgtgt', 'spice', 'tender', 'meat', 'aroma', 'everything', 'good', 'stalker', 'metro', 'fallout', 'want', 'hear', 'opinion', 'game', 'funniest', 'comment', 'get', 'free', 'helpful', 'award', 'really', 'need', 'laugh', 'e', 'lalalalalalalalalalalalalalalalalalalalalalala', 'brbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrb', 'dont', 'like', 'emoji', 'make', 'exception', 'one', 'williams', 'got', 'investment', 'dont', 'know', 'investment', 'go', 'williams', 'go', 'ucolstarfish', 'favorite', 'editor', 'ucolstarfish', 'favorite', 'editor', 'ill', 'best', 'user', 'teenager', 'competitor', 'turned', 'stone', 'methodsjust', 'purely', 'theoretic', 'discussion', 'easiest', 'way', 'would', 'preferred', 'way', 'least', 'impact', 'family', 'least', 'destruction', 'body', 'sleeping', 'pillow', 'kill', 'effectively', 'using', 'sleeping', 'pill', 'alcohol', 'like', 'vodka', 'dont', 'want', 'end', 'vegetable', 'hold', 'back', 'thats', 'im', 'asking', 'friend', 'someone', 'please', 'please', 'tell', 'tom', 'good', 'person', 'want', 'stop', 'want', 'it', 'stop', 'b', 'ad', 'im', 'scared', 'would', 'happen', 'want', 'dont', 'know', 'hurt', 'friend', 'hey', 'stalked', 'fault', 'first', 'place', 'c', 'saw', 'lie', 'lie', 'lie', 'lie', 'lie', 'dont', 'think', 'gd', 'want', 'anymore', 'think', 'im', 'supposed', 'gone', 'mg', 'canal', 'thinking', 'taking', 'dont', 'know', 'im', 'even', 'posting', 'much', 'hurt', 'everyday', 'sleep', 'peace', 'want', 'forever', 'day', 'one', 'posting', 'something', 'interesting', 'happens', 'qwertyiopasdfghjklzxcvbnm', 'guess', 'cant', 'sleep', 'supposed', 'die', 'sleep', 'cant', 'sleep', 'dont', 'think', 'ill', 'itis', 'awfully', 'tempting', 'though', 'going', 'rough', 'patch', 'see', 'reason', 'one', 'actually', 'love', 'everyone', 'faking', 'caring', 'men', 'one', 'actually', 'care', 'listen', 'understand', 'im', 'fault', 'everything', 'nothing', 'reversible', 'nothing', 'make', 'happy', 'absolutely', 'nothing', 'plan', 'go', 'outside', 'city', 'hang', 'tree', 'even', 'picked', 'specific', 'tree', 'easy', 'climb', 'place', 'tie', 'rope', 'thick', 'enough', 'hold', 'weight', 'reason', 'left', 'here', 'year', 'half', 'long', 'relationship', 'ended', 'peoplethink', 'im', 'takinglying', 'suicidal', 'family', 'splitting', 'sexual', 'assault', 'school', 'suck', 'anyone', 'talk', 'im', 'close', 'want', 'either', 'go', 'away', 'ill', 'make', 'go', 'away', 'im', 'therapy', 'men', 'kinda', 'gone', 'last', 'resort', 'time', 'police', 'hospital', 'finally', 'told', 'crush', 'liked', 'like', 'back', 'im', 'super', 'happy', 'dd'] 670